TileDB-Inc/TileDB-VCF

libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/test/src/unit-c-api-reader.cc

This allows TileDB-VCF to work with TileDB Cloud for exports.

Remove VFS usage from dataset open.

---

libtiledbvcf/src/c_api/arrow.h

This calculation needs to return the number of uint8 elements required to store a nullable bitmask for a given number of records, which is "ceil(num_records, 8)" using the internal ceil function.
For #47: compatibility with arrow 0.15 release and current trunk, where additional consistency checks have been added.

Fix calculation of null bitmask buffer size

---

libtiledbvcf/src/c_api/arrow.h
libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h
libtiledbvcf/src/utils/utils.cc
libtiledbvcf/src/utils/utils.h

This PR is not ideal but is required for better cloud array support until TileDB Cloud supports proper groups.
The two arrays that make up a TileDBVCF dataset must be register with the same base path and then their sub-directories using "-" in place of "/".
That is a dataset with a base URI of
`s3://mybucket/vcf-samples-20`
and the arrays are actually located at:
`s3://mybucket/vcf-samples-20/data`
`s3://mybucket/vcf-samples-20/metadata/vcf_headers`
yields the following two registration names in the cloud service:
`tiledb://namespace/vcf-samples-20-data`
`tiledb://namespace/vcf-samples-20-metadata-vcf_headers`

Support reads from cloud register datasets

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/vcf/vcf.cc

Check return values for several more functions. HTSLIB sets '__attribute__((warn_unused_result))' on these functions, which leads to a build error for the existing code under conda's GCC.

Fix build errors w/ -Wall

---

libtiledbvcf/src/utils/sample_utils.cc
libtiledbvcf/src/utils/sample_utils.h
libtiledbvcf/src/utils/utils.h
libtiledbvcf/src/write/writer.cc

Previously we batched on tile size but did not check tile boundaries. This led to cases where we tried to load across the tile extent and caused a ordering problem with global order writes.
The new batching can lead to degraded performance if a user issues a store request in which the samples all fall onto individual tile extents. The decision was made to be robust and support loading in this case, and to instruct users ahead of time for best performance to load batches that align with complete tile extents (10 samples).

Batches need to not cross tile boundaries

---

.azure-pipelines.yml
apis/python/conda-env.yml
apis/python/setup.py
ci/azure-linux_mac.yml

- Get libtiledbvcf from environment (PREFIX) if available
- Use -g and -O0 with debug option
- Don't overlink the arrow core library
- Bump the pyarrow minimum version to fix test errors

More conda build fixes

---

libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/read/reader.h

In the destructor we only make sure any async queries that are active finish before allow everything to be cleaned up. This prevent deleting the attribute/coords buffers from an active tiledb query.

Add destructor for reader

---

libtiledbvcf/src/read/reader.cc

This change alters the behavor of read_current_batch to properly handle cases we the tiledb vcf query is incomplete but we've moved to a new underlying tiledb core query. Previously we incorrectly checked the query_results which showed a complete query, ignoring that we had allocated and setup a new Query object and that the query_results was invalid.

Check tiledb query status in read_current_batch

---

apis/python/tests/test_tiledbvcf.py
libtiledbvcf/src/read/reader.cc

This is an optimization for more efficient partitioning to limit the regions to those that are within or contain the nonEmptyDomain. This allows for more balanced partitioning by discarding regions which are known to have no results.

Filter contigs for read to nonEmptyDomain

---

libtiledbvcf/src/read/reader.cc

Resetting these in read_current_batch causes results to be overridden if we hit a case where the TileDB query is completed but the vcf read is not AND the user's buffers are not filled. In that cases we previously would (correctly) start a new TileDB query but incorrectly reset the buffers, thus overriding the last bit of results from the previously completed TileDB query.

Reset current buffer sizes only in read

---

apis/spark/src/main/java/io/tiledb/libvcfnative/NativeLibLoader.java

This PR contains the changes required for the determination of the exact versioned name of the `libtiledb.so`. Tested both on OSX and Ubuntu.
ClubHouse Link: https://app.clubhouse.io/tiledb-inc/story/1703/determine-native-libtiledb-library-in-tiledb-vcf

Determine native libtiledb library in TileDB [ch1703]

---

apis/python/src/tiledbvcf/binding/libtiledbvcf.cc
apis/python/src/tiledbvcf/binding/writer.cc
apis/python/src/tiledbvcf/binding/writer.h
apis/python/src/tiledbvcf/dataset.py
libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake
libtiledbvcf/src/c_api/tiledbvcf.cc
libtiledbvcf/src/c_api/tiledbvcf.h
libtiledbvcf/src/c_api/tiledbvcf_enum.h
libtiledbvcf/src/cli/tiledbvcf.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h
libtiledbvcf/src/vcf/vcf.cc
libtiledbvcf/src/write/writer.cc
libtiledbvcf/src/write/writer.h
libtiledbvcf/test/src/unit-c-api-writer.cc

The underlying TileDB arrays will have a sha256 checksum filter enabled by default on all fields, coordinates and offsets with an new CLI option `--checksum` to allow the user to set the checksum to md5/sha256 or none.

Add checksum filter support

---

libtiledbvcf/src/read/reader.cc

Samples list vector should cover entire range of requested sample ids.

Samples list vector should cover entire range of requested sample ids

---

libtiledbvcf/test/run-cli-tests.sh

This adds a test for the segfault fixed in #79.

Add export test with non-contiguous samples

---

libtiledbvcf/CMakeLists.txt
libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake
libtiledbvcf/src/dataset/attribute_buffer_set.cc
libtiledbvcf/src/dataset/attribute_buffer_set.h
libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h
libtiledbvcf/src/read/in_memory_exporter.cc
libtiledbvcf/src/read/read_query_results.cc
libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/write/writer_worker.cc
libtiledbvcf/test/src/unit-c-api-reader.cc

Instead of using the TILEDB_COORDS buffer now sample and end_pos are queried as independent buffers. This if a feature allowed in TileDB 2.0.0 which will improve performance and memory usage.
~We will wait to merge this until an official TileDB 2.0.0 release (which should be in a few days) and the TileDB superbuild verison will be updated then.~ TileDB 2.0.0 is released and this PR has been updated.

Update to split coordinates for TileDB 2.0.0

---

apis/java/build.gradle
apis/spark/build.gradle

This allows the for the version to be automatically detected from the latest git tag

Use gradle-git-version for java/spark versioning

---

.git_archival.txt
.gitattributes
apis/python/conda-env.yml
apis/python/setup.py

This is needed for conda package building.

Add support for github tar archives in building

---

.azure-pipelines.yml
ci/build-images.yml

This updates the CI pipeline to build and push the docker images. It's setup so that images are only built when:
* `master` is updated, which will tag the image as `latest`, or
* a new `tag` is pushed, in which case the image is tagged with the tag version
Image building is implemented as a separate job, which depends on the *Build* job completing successfully. 
All 3 Dockerfiles are built in parallel, however, the python and dask images are commented out because they need to be updated.
Before merging this we need to

Add CI job to build Dockerfiles

---

apis/python/setup.py

A couple small fixes:
- Setting `FORCE_EXTERNAL_HTSLIB=OFF` was ignored
- Several overrides were being passed to cmake in duplicate

Fix cmake overrides for python setup

---

apis/spark/build.gradle

The default assemble jar will have `-default` added.

Build the shadowJar without a classifier

---

apis/spark/build.gradle

Mark spark libraries as compileOnly for spark api

Mark spark libraries as compileOnly for spark api 

---

.azure-pipelines.yml
.dockerignore
docker/Dockerfile-cli
docker/Dockerfile-py
docker/README.md
libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

- Updates TileDB to 2.0.1 for superbuild
- Updates to latest miniconda3 image (v4.8.2)
- Installs HTSlib w/ conda rather than compiling as an external project and removes its systems deps
- Uses `cmake` from conda to (avoids issues compiling against libcurl)
- Removes redundant `conda install dask` step (it's already included in `conda-env.yml`)
- `Dockerfile-cli` should now be built using the project root directory as the context (to be consistent with `Dockerfile-py`)

Fix and update Dockerfile-py

---

libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/read/reader.h

The reader fetches one or more intersecting regions to a given gVCF range. It
iterates through each intersecting region, report its respective cell in-place.
If we overflow while reporting one of these regions, the reader aborts and
returns incomplete to the user. When the reader continues the read, the reader
will start from the same gVCF range, re-reporting all intersecting regions that
precede the region that overflowed the previous read.
To fix this, we save the index of the region that caused the overflow. On the
next read, we start at this region instead of from the first region that
intersects the gVCF range.

Fix duplicate cell reporting between incomplete queries

---

libtiledbvcf/src/dataset/attribute_buffer_set.cc

When VCF is given a memory budget of N, N/2 is given to the core while
the other N/2 are given to the VCF reader.
The VCF reader allocates M attribute buffers, where each buffer should have
a size of (N/2)/M, but it currently is allocated N/2 for _each_ buffer,
which over-allocates the VCF reader by a scale of M.
This fixes the issue.

Fix over-allocating attribute buffers

---

libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/read/reader.h

The CLI supports a flag to report a whitelist of sample names:
`-s, --sample-names   CSV list of sample names to export`
Currently, it reports all samples but reports the names of the filtered samples
as an empty string. For instance, `--sample-names v2-tJjMfKyL,v2-ZVudhauk`
exports the following TSV:
```
SAMPLE  CHR     POS
v2-ZVudhauk     chr1    1
chr1    1
chr1    1
chr1    1
chr1    1
chr1    1
v2-tJjMfKyL     chr1    1
<snip>
```
The `v2-ZVudhauk` sample has an id of 10 and `v2-tJjMfKyL` has an id of 16,
the missing sample names correspond to samples 11-15, inclusively.
The expected output is:
```
SAMPLE  CHR POS
v2-ZVudhauk chr1  1
v2-tJjMfKyL chr1  1
<snip>
```
There are two parts to this bug:
1. Within `Reader::next_read_batch()`, the `read_state_.current_samples` "map"
(really a …

Fix selective sample exports

---

apis/spark/src/main/java/io/tiledb/vcf/Util.java
apis/spark/src/main/java/io/tiledb/vcf/VCFInputPartitionReader.java
apis/spark/src/test/java/io/tiledb/vcf/UtilTest.java

Added `getDefaultRecordByteCount` method that gets the record size in bytes, given a specific Arrow Vector class.

Added getDefaultRecordByteCount method

---

.dockerignore
README.md
docker/Dockerfile-cli
docker/Dockerfile-dask-py
docker/Dockerfile-py
docker/README.md

New [README](https://github.com/TileDB-Inc/TileDB-VCF/blob/aw/ch2596/docker-quickstart/docker/README.md) for Dockerfiles that includes a quick start guide for `tiledbvcf-py` and `tiledbvcf-cli`. Mainly intended for Docker Hub. 
Other changes:
- final working directory is now `/data` rather than `/temp`
- `tiledbvcf-py` can be used to execute a script or launch an interactive session
- set `AWS_EC2_METADATA_DISABLED` env variable to avoid slow down caused by the (typically) necessary API calls

Overhaul Dockerfile READMEs

---

apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.c
apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.h
apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.java
apis/java/src/main/java/io/tiledb/libvcfnative/NativeLibLoader.java
apis/java/src/main/java/io/tiledb/libvcfnative/VCFReader.java
apis/java/src/test/java/io/tiledb/libvcfnative/VCFReaderTest.java
apis/spark/src/main/java/io/tiledb/util/CredentialProviderUtils.java
apis/spark/src/main/java/io/tiledb/vcf/VCFDataSourceOptions.java
apis/spark/src/main/java/io/tiledb/vcf/VCFDataSourceReader.java
apis/spark/src/main/java/io/tiledb/vcf/VCFSparkSchema.java
apis/spark/src/test/java/io/tiledb/vcf/VCFDatasourceTest.java
libtiledbvcf/src/c_api/tiledbvcf.cc
libtiledbvcf/src/c_api/tiledbvcf.h
libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h
libtiledbvcf/src/read/bcf_exporter.cc
libtiledbvcf/src/read/bcf_exporter.h
libtiledbvcf/src/read/exporter.h
libtiledbvcf/src/read/in_memory_exporter.cc
libtiledbvcf/src/read/in_memory_exporter.h
libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/read/reader.h
libtiledbvcf/src/read/tsv_exporter.cc
libtiledbvcf/src/read/tsv_exporter.h
libtiledbvcf/test/src/unit-c-api-reader.cc

Allow spark schema to be dynamic based on materialized attributes and available fmt/info fields. A `select *` in spark will now pull in all available fields and a `df.schema()` will describe and show all possible fields.
Fields are still pushed down so a select with a fixed set of attributes will not select all possible fields.

Allow spark schema to be dynamic

---

apis/python/src/tiledbvcf/__init__.py
apis/python/src/tiledbvcf/dask_functions.py
apis/python/src/tiledbvcf/dataset.py
apis/python/tests/test_dask.py
apis/python/tests/test_tiledbvcf.py

Rename python TileDBVCFDataset to Dataset. TileDBVCFDataset is left with a deprecation warning.

Rename python TileDBVCFDataset to Dataset

---

libtiledbvcf/src/write/writer_worker_v3.cc

This fixes an instance of accessing a reference to a node in the record
heap after it has been popped (and freed). In my testing, this manifests as
adding extraneous records to the heap, causing a failure when trying to read
more than exists from the buffered VCF records:
`Error getting contig name from VCF; current record is null.`

Use-after-free in record heap

---

libtiledbvcf/src/utils/sample_utils.h
libtiledbvcf/src/vcf/vcf.cc
libtiledbvcf/src/vcf/vcf.h

Currently, we buffer VCF records into memory and store the minimum start
position and maximum end position of these buffered records. When we iterate
to buffer the next set of VCF records, we seek to the maximum end position
and read from there. This breaks if there are any overlapping records.
This patch chanes the behavior from open+seek on each iteration to opening
once on the first iteration and making use of the internal htslib iterator
to move between records.

VCF record iteration for overlapping records

---

libtiledbvcf/src/cli/tiledbvcf.cc

If no samples are given now all samples in the array are exported

Remove forcing user to set samples for cli export

---

apis/python/src/tiledbvcf/binding/libtiledbvcf.cc
apis/python/src/tiledbvcf/binding/writer.cc
apis/python/src/tiledbvcf/binding/writer.h
apis/python/src/tiledbvcf/dataset.py
libtiledbvcf/src/c_api/tiledbvcf.cc
libtiledbvcf/src/c_api/tiledbvcf.h
libtiledbvcf/src/write/writer.cc
libtiledbvcf/src/write/writer.h

Add python support for scratch space
Two new parameters are added to the ingest_samples for `scratch_space_path` and `scratch_space_size`. A c-api is also exposed.

 Add python support for scratch space

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc

Handle pos -> pos_start in queryable attribute list, this fixes a problem with sparks schema for end_position based arrays.

Handle pos -> pos_start in queryable attribute list

---

apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.c
apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.h
apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.java
apis/java/src/main/java/io/tiledb/libvcfnative/VCFReader.java
apis/python/src/tiledbvcf/binding/libtiledbvcf.cc
apis/python/src/tiledbvcf/binding/reader.cc
apis/python/src/tiledbvcf/binding/reader.h
apis/python/src/tiledbvcf/binding/writer.cc
apis/python/src/tiledbvcf/binding/writer.h
apis/python/src/tiledbvcf/dataset.py
apis/spark/src/main/java/io/tiledb/vcf/VCFDataSourceOptions.java
apis/spark/src/main/java/io/tiledb/vcf/VCFInputPartitionReader.java
libtiledbvcf/src/c_api/tiledbvcf.cc
libtiledbvcf/src/c_api/tiledbvcf.h
libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/read/reader.h
libtiledbvcf/src/write/writer.cc
libtiledbvcf/src/write/writer.h

Add option to enable verbose output for spark and python. Python supports verbose output for reader and writer. Spark is reader only. This is helpful in debugging.
Python has a new parameter for the `Dataset` constructor.
Spark as a new driver option `verbose` , `.option("verbose", true)`

Add option to enable verbose output for spark and python

---

libtiledbvcf/src/CMakeLists.txt
libtiledbvcf/src/cli/tiledbvcf.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h
libtiledbvcf/src/read/exporter.h
libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/utils/sample_utils.cc
libtiledbvcf/src/utils/sample_utils.h
libtiledbvcf/src/vcf/htslib_value.h
libtiledbvcf/src/vcf/vcf_utils.cc
libtiledbvcf/src/vcf/vcf_utils.h
libtiledbvcf/src/vcf/vcf_v2.cc
libtiledbvcf/src/vcf/vcf_v2.h
libtiledbvcf/src/vcf/vcf_v3.cc
libtiledbvcf/src/vcf/vcf_v3.h
libtiledbvcf/src/write/record_heap_v2.cc
libtiledbvcf/src/write/record_heap_v2.h
libtiledbvcf/src/write/record_heap_v3.cc
libtiledbvcf/src/write/record_heap_v3.h
libtiledbvcf/src/write/writer.cc
libtiledbvcf/src/write/writer_worker_v2.cc
libtiledbvcf/src/write/writer_worker_v2.h
libtiledbvcf/src/write/writer_worker_v3.cc
libtiledbvcf/src/write/writer_worker_v3.h
libtiledbvcf/test/src/unit-vcf-iter.cc

This is a prerequisite to ingesting overlapping records.
Currently, the `VCF` class iterates through a VCF file with a readahead that
buffers multiple records into a single buffer. When the last record in the
buffer is read, the buffer is cleared and populated with the next set of
records. This is OK because we currently enforce that all records are ordered
and without overlap.
To support overlapping records, records may be processed out-of-order. We can
not safely clear the single buffer because nodes on the heap may still point
to them. This change moves ownership of the records from the `VCF` instance
to the individual nodes on the heap.
The `VCF` still performs a readahead, but places each record onto a queue. The
writer worker will pop the next record and place it into the heap. When …

Heap-node ownership of buffered records

---

libtiledbvcf/src/read/in_memory_exporter.cc

We encode and store INFO values in a buffer as: keystr,type,nvalues,values
This fixes an off-by-one where we read an extra INFO value from the query
result. If the overread memory is zeroed, the behavior works as expected. If
the memory is not-zeroed, we end up with a segfault. I could also envision
corrupt/false values being read, but I have not explicitly observed that
scenario.

Fix segfault in InMemoryExporter::get_info_fmt_value

---

apis/python/src/tiledbvcf/binding/libtiledbvcf.cc
apis/python/src/tiledbvcf/binding/reader.cc
apis/python/src/tiledbvcf/binding/reader.h
apis/python/src/tiledbvcf/dataset.py
apis/python/tests/test_tiledbvcf.py

New `attributes()` method for `tiledbvcf.Dataset` that allows users to retrieve attributes available in a dataset. 
* by default all attributes are returned (with the exception of the aggregated `info` and `fmt` attributes)
* specific subsets of attributes can be selected with the `attr_type` argument

Add python method for retrieving attributes from a dataset

---

libtiledbvcf/src/write/writer.cc

This was a debugging line that slipped in with 5186d2f937de4ac461d4814a3342bc734d7c1f23.

Restore threading to the ingestion path

---

apis/spark/src/main/java/io/tiledb/vcf/VCFDataSourceReader.java
apis/spark/src/test/java/io/tiledb/vcf/VCFDatasourceTest.java

If a user passes both a sample option (`sampleFile` or `samples`) and then they try to add a predicated filter in a where clause return an error to the user. When both a sample option and a predicate are passed we can't know which (or all) of the samples the user was trying to access. The safest option is to error and force the user to set either a where clause or an option only.

Error in spark for sample option and filter

---

apis/python/src/tiledbvcf/binding/libtiledbvcf.cc
apis/python/src/tiledbvcf/binding/reader.cc
apis/python/tests/test_tiledbvcf.py
libtiledbvcf/src/c_api/tiledbvcf.cc
libtiledbvcf/src/c_api/tiledbvcf.h
libtiledbvcf/src/read/in_memory_exporter.cc
libtiledbvcf/src/read/in_memory_exporter.h
libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/read/reader.h

This is useful when a user is reusing a dataset object from python but wants to change the attributes that are being queried.

Add new function for resetting reader's buffers

---

apis/python/src/tiledbvcf/dataset.py
apis/python/tests/test_tiledbvcf.py

This joins #132 to prevent users from directly passing sample names along with a sample file when querying from python. Previously, values from the two arguments would be merged.

Make dataset.read()'s sample arguments mutually exclusive

---

libtiledbvcf/src/read/reader.cc

There is no need to take a reference as the query object is already stored as a pointer. Taking a reference causes crashes as the pointer to pointer becomes invalid when the function goes out of scope.

Don't take reference to query in reader futures

---

libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

This fixes a hang that was occurring in spark.

Update To TileDB 2.0.7

---

libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

TileDB 2.0.8 includes fixes for GCS (which is not enabled here), a curl change for TileDB Cloud and a split of posix file permissions vs directory permissions.

Update to TileDB 2.0.8

---

libtiledbvcf/src/enums/attr_datatype.h
libtiledbvcf/src/read/in_memory_exporter.cc

Arrow expects that null values will have a 1 element place still held in the buffer for the index position. Make sure this happens in all cases.
Previously fmt/info fields might not properly set the element or byte count to 1 value. This caused these fields to be shifted in spark by however many nulls were present.

Always placehold a spot for null values in buffer

---

libtiledbvcf/src/read/reader.cc
libtiledbvcf/test/src/unit-c-api-reader.cc

There is no need to call `init_tiledb()` and recreate the context for all possibly parameter change functions. These calls will be done before the dataset is opened and a reader returned. Avoiding these calls avoids a problem of initializing TBB twice with different thread counts.
`init_tiledb()` is left for the bed_file and sample_file setters as those need VFS enabled to validate the files exist. These functions should only be called after the dataset is opened and a reader object is returned, so the code paths should never hit in normal api usage.

Delay creating contexts for read

---

README.md
docker/README.md

- update references to `vcf-samples-20` with the new v3 URI
- swap deprecated `TileDBVCFDataset` class for `Dataset` in READMEs

Update READMEs for 0.5

---

apis/python/src/tiledbvcf/binding/reader.cc

Calling `.release()` un-tracks the buffer from the python perspective. Calling `clear` on the
buffer vector will release the python refcount correctly.
[ch3031]

Fix buffer memory leak

---

apis/spark/src/main/java/io/tiledb/vcf/VCFDataSourceOptions.java
apis/spark/src/test/java/io/tiledb/vcf/VCFDataSourceOptionsTest.java

Previously spark used "ranges" as the option for specifying regions. This was inconsistent with other apis. Now spark accepts both ranges and regions to be inline with other APIs and not break backwards compatibility.

Change `ranges` to `regions` in the Spark API

---

libtiledbvcf/src/cli/tiledbvcf.cc

I took a page from bedtools and named the flag `--sorted`, indicating the user-provided regions are already sorted. But I'm open to other suggestions.
Also updated the docs for `--no-duplicates` w/ start-based indexing.

Add CLI flag to skip region sorting

---

.azure-pipelines.yml

Docker images are now built in a separate stage when the Build stage succeeds or is skipped. As before, images are only pushed to docker hub on master or with a new ref/tag

Separate CI stage for building docker images

---

libtiledbvcf/src/htslib_plugin/hfile_tiledb_vfs.c

Use the default HTSLIB read capacity size. We always should have been signalling to htslib to use the default 32kb capacity.

Use the default HTSLIB read capacity size

---

libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/read/reader.h

In v3 arrays the sort on the start instead of end means that we can't use the end position crossing to a new region to bump the minimum region checked for intersection. We need to instead wait for the start position to move to a new minimum region before shifting.
Limiting the regions we check for intersections is an optimization to limit the search domain as we move through the results of the query.

V3 Arrays should move regions based on start_pos

---

.dockerignore
docker/Dockerfile-py

Builds were failing because conda started installing an older version of htslib (v1.3) that lacks some of the logging features we use. This sets the minimum version to 1.8, which is what use in the superbuild.

Define minimum version of htslib from conda in python dockerfile

---

libtiledbvcf/src/read/reader.cc

We can not move the minimum region index as we iterate TileDB query results because the results are unordered. Instead we need to check each cell against all relevant regions. Relevant regions are determined by doing a binary search to find the first possible region that will intersect. The algorithm is unchanged after the binary search.
This change effects both v2 and v3 read algorithms

Every record needs to independently check regions for intersections

---

apis/python/src/tiledbvcf/binding/libtiledbvcf.cc
apis/python/src/tiledbvcf/binding/reader.cc
apis/python/src/tiledbvcf/binding/reader.h
apis/python/src/tiledbvcf/dataset.py
apis/python/tests/test_tiledbvcf.py
libtiledbvcf/src/c_api/tiledbvcf.cc
libtiledbvcf/src/c_api/tiledbvcf.h
libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h
libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/read/reader.h

Adds the following python methods (as well as the requisite C APIs):
- `dataset.samples()`
- `dataset.schema_version()`
Retrieving the dataset's schema version may not be all that useful on its own but I plan on using it in a higher-level `describe()` function.

New C/Python APIs for retrieving dataset schema version and sample names

---

libtiledbvcf/cmake/Modules/FindCatch_EP.cmake
libtiledbvcf/test/src/unit-c-api-reader.cc
libtiledbvcf/test/src/unit-helpers.h
libtiledbvcf/test/src/unit-vcf-export.cc

Since there is no ordering of VCF results, we switch to use a struct that represents a VCF record. Then we use Catch2's `UnorderedEquals` matcher to compare expected results to actual ignoring any record ordering differences. We also switch the vcf export tests to handle unordered comparison of results.

Update C++ tests for unordered vector of results

---

libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/read/reader.h

There is a bug in the existing intersection reads, in that we don't properly limit exporting duplicate records from anchors. The
last_exported_end does not correctly handle anchors, and has problems because TileDB query results are unordered. Instead a new formula for checking intersection which is more generic and guaranteed to not have issue with anchors or duplicates.
Depends on #171

Update v2/v3 reads to use new intersection algorithm

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h
libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/read/reader.h
libtiledbvcf/test/src/unit-vcf-store.cc

Instead of issueing a range query for all samples between the min id and max id, we instead will issue points for all samples. In TileDB 2.1 point ranges can be coalesced automatically. In the worst case before if a user issues a query for 2 samples, the first and last TileDB-VCF would being in the entire dataset. Now it will just be the two samples needed.
This depends on the unmerged #169 .

Switch to using point ranges for all sample ids

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h
libtiledbvcf/src/read/reader.cc

For v2/v3 arrays we need to validate region is same contig as record by checking the names. Even with global ordering in v2/v3 arrays its possible for a region to incorrectly overlap because a record extends before or after a contigs boundaries. Contig offsets are not guaranteed to be unique so we use a string comparison of the contig name.

Validate region has same contig as record

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h
libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/read/reader.h
libtiledbvcf/test/src/unit-vcf-store.cc

This PR reduces the number of times we open an array. First we stop reopening the array for every TileDB query (read partition). Next we create TileDBVCFDataset class members to hold the open VCF header and data arrays so we don't have to open those in multiple places.
If the user has a lot of fragment and not consolidated the fragment metadata opening the array can be costly. While the user should consolidate the fragment metadata, we can also avoid opening the array so many times to help.

Reduce Number of Time Array Is Opened

---

libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/read/reader.h

This allows for better long term backwards compatibility of these functions. Too much was different in them and it is cleaner to split
them into versions based on the dataset version.

Split init_for_reads/next_read_batch into versions

---

ci/azure-linux_mac.yml
ci/native_libs-linux_osx.yml

Reverts TileDB-Inc/TileDB-VCF#203
This was fixed upsteam.

Revert "Workaround homebrew openssl error for CI"

---

libtiledbvcf/src/vcf/vcf_v4.cc
libtiledbvcf/src/vcf/vcf_v4.h

Previously it was possible for the VCF record to read beyond the contig seeked too. If the queue was empty then then vcf class would resume reading but it always checked the first record's contig. This might be a different contig then the record was suppose to be tracking.

Set the contig for ingestion on seek of VCF file

---

apis/python/tests/test_tiledbvcf.py

TileDB results are necessarily ordered so we should sort the pandas dataframes so we can handle the comparison regardless of result ordering.

Sort pandas dataframes for unordered comparison

---

apis/python/tests/test_tiledbvcf.py
libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/read/reader.h

In v4 since we have strings core will not coalesce the point ranges. In the special case that we are exporting all samples, we can optimize by only setting one range with the first and last sample of the partition/batch.

Handle all sample export for v4 with optimal range

---

libtiledbvcf/src/write/writer.cc
libtiledbvcf/src/write/writer_worker.h
libtiledbvcf/src/write/writer_worker_v2.h
libtiledbvcf/src/write/writer_worker_v3.h
libtiledbvcf/src/write/writer_worker_v4.h

Add write message for verbose ingestion details. This is similar to the export logs of "processed X cells in Y time".

Add write message for verbose ingestion

---

libtiledbvcf/src/c_api/tiledbvcf.cc
libtiledbvcf/src/c_api/tiledbvcf.h
libtiledbvcf/src/cli/tiledbvcf.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h
libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/read/reader.h
libtiledbvcf/src/write/writer.cc
libtiledbvcf/src/write/writer.h

By default we will not longer collect tiledb statistics for the vcf header access. Most of the time this just pollutes the TileDB stats when trying to inspect the data array access.
Depends on #210 due to conflicts

Add option for enable/disable of vcf header stats

---

libtiledbvcf/src/cli/tiledbvcf.cc
libtiledbvcf/src/write/writer.cc
libtiledbvcf/src/write/writer.h
libtiledbvcf/src/write/writer_worker.h
libtiledbvcf/src/write/writer_worker_v2.cc
libtiledbvcf/src/write/writer_worker_v3.cc
libtiledbvcf/src/write/writer_worker_v4.cc

Add CLI option for max TileDB buffer size for ingestion. Previously this was hard coded to 1GB.

Add CLI option for max TileDB buffer size for ingestion

---

libtiledbvcf/src/read/reader.cc

Users can still partition the read but we don't sub-divide a partition by the sample batch count (tile extent). This is not longer needed nor optimal in v4 arrays because sample is now the last dimension.

Don't batch v4 reads by samples

---

libtiledbvcf/src/write/writer.cc
libtiledbvcf/src/write/writer.h

V4 writes should split fragments by contig since we now query only on contig.
This is based on #214 since I needed the `region.seq_name` from the worker, which I added there. I'll rebase once #214 is merged.

V4 writes should split fragments by contig 

---

libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

Update to TileDB 2.1.4 for performance boost with new 3D array and string dimensions.

Update to TileDB 2.1.4

---

libtiledbvcf/src/write/writer.cc
libtiledbvcf/src/write/writer.h

The finalize calls on all the fragments can add up to detrimental performance because it blocks further writes. This change launches all finalizes in separate non-blocking threads.

Parallelize finalize calls for v4

---

libtiledbvcf/src/vcf/vcf_v3.cc
libtiledbvcf/src/vcf/vcf_v4.cc
libtiledbvcf/src/write/writer_worker_v2.cc
libtiledbvcf/src/write/writer_worker_v3.cc
libtiledbvcf/src/write/writer_worker_v4.cc

Properly exit early when sample is missing contig. We also properly reset the queue on seeking a new contig in case of early exit in seek to not leave old/invalid records on the queue.
This issue has existed in all versions, but only manifested in errors due to v4's splitting of a write per contig.
A unit test is not added because I'm unsure of the license of the data that produced this bug. I've been trying to create a synthetic  VCF to replicate but I'll wait for @aaronwolen 's expertise next week to help.

Properly exit early when sample is missing contig

---

apis/python/src/tiledbvcf/binding/libtiledbvcf.cc
apis/python/src/tiledbvcf/binding/writer.cc
apis/python/src/tiledbvcf/binding/writer.h
apis/python/src/tiledbvcf/dataset.py
libtiledbvcf/src/c_api/tiledbvcf.cc
libtiledbvcf/src/c_api/tiledbvcf.h
libtiledbvcf/src/cli/tiledbvcf.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h
libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/write/writer.cc
libtiledbvcf/src/write/writer.h
libtiledbvcf/test/src/unit-vcf-store.cc

This allow for setting the number of samples to batch per ingestion. This removes the parameter from the create of the dataset as its no longer required to be uniform for all ingestions.
This also adds the equivalent c-api and support in python.

Add new `--sample-batch-size` for store command

---

apis/java/src/main/java/io/tiledb/libvcfnative/NativeLibLoader.java
libtiledbvcf/cmake/Modules/FindHTSlib_EP.cmake

There is a few improvements in HTSLIB but most importantly a bug fix in double free in hts_iter_destroy. Version 1.10 was selected as this has been previously validated by @aaronwolen .

Update HTSLIB to 1.10

---

libtiledbvcf/src/cli/tiledbvcf.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h
libtiledbvcf/test/CMakeLists.txt
libtiledbvcf/test/src/unit-vcf-utils.cc

A new CLI command is added for supporting array fragment consolidation, and array fragment metadata consolidation. The equivalent vacuum functions are also implemented. Most users will want to periodically consolidate the fragment metadata in order to improve performance with the large number of fragments.
Usage:
```
tiledbvcf utils consolidate fragment_meta -u <array>
tiledbvcf utils consolidate fragments -u <array>
tiledbvcf utils vacuum fragment_meta -u <array>
tiledbvcf utils vacuum fragments -u <array>
```

Add new utils cli command for consolidate/vacuum

---

libtiledbvcf/src/CMakeLists.txt
libtiledbvcf/src/cli/tiledbvcf.cc

We now first try to get the tag name from git before settling on the sha when TileDB-VCF is not built on a release tag.

Adjust TileDB-VCF version printing for tag name

---

.azure-pipelines.yml

This drops the `succeeded()` condition on the `BuildNativeLibs` stage. The `succeeded()` requires all previous stages to succeed which does not work for tags because the first CI stage of the unit tests are skipped. This means we are not building the multi-lib jar for spark and instead are only building linux. This commit solves this problem.

Fix native library building for tags

---

.dockerignore
docker/Dockerfile-cli
docker/README.md

- updates the CLI Dockerfile to utilize multi-stage builds significantly shrinking the size of the final image (860Mb -> 187Mb)
- copies over `.git` so TileDB-VCF's version is now recorded at build time
- adds an example of creating an array with Docker, highlighting the need to specify user/group IDs to avoid permission issues

Multi-stage build for CLI docker image

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/utils/sample_utils.cc
libtiledbvcf/src/utils/sample_utils.h
libtiledbvcf/src/utils/utils.cc
libtiledbvcf/src/utils/utils.h
libtiledbvcf/src/vcf/vcf_v4.cc
libtiledbvcf/src/vcf/vcf_v4.h
libtiledbvcf/src/write/writer.cc
libtiledbvcf/src/write/writer.h

If no scratch space is given we will automatically use the HTSLIB VFS plugin to remotely read sample files. This can be advantageous to remove the local temporary storage requirement during registration/ingestion.
This also fixes three places where we arbitrarily where checking for s3 paths and not any other remote file system. We will now properly support all files systems that core TileDB supports.
Note: The performance for reading remote samples leaves significant room for improvement, as such marking this as a draft.

 Add support for reading samples remote

---

apis/python/src/tiledbvcf/dataset.py
apis/python/tests/test_tiledbvcf.py

This adds a new `create_dataset()` method to the `Dataset` class, separating the creation and ingestion stages, as we do w/ the CLI.
The primary motivation is to create a cleaner separation between each stage's respective parameters, which will be added in subsequent PRs.

Separate python methods for dataset creation and ingestion

---

apis/python/src/tiledbvcf/binding/libtiledbvcf.cc
apis/python/src/tiledbvcf/binding/writer.cc
apis/python/src/tiledbvcf/binding/writer.h
apis/python/src/tiledbvcf/dataset.py
libtiledbvcf/src/c_api/tiledbvcf.cc
libtiledbvcf/src/c_api/tiledbvcf.h
libtiledbvcf/src/write/writer.cc
libtiledbvcf/src/write/writer.h

Extends the C API to allow setting the following dataset creation/ingestion parameters and exposes them to Python:
**Creation parameters**
- `anchor_gap`
- `tile_capacity`
**Ingestion parameters**
- `num_threads`
- `thread_task_size`
- `memory_budget_mb`
- `max_buffer_limit`

C/Python APIs for writer config params

---

apis/python/src/tiledbvcf/binding/libtiledbvcf.cc
apis/python/src/tiledbvcf/binding/writer.cc
apis/python/src/tiledbvcf/binding/writer.h
apis/python/src/tiledbvcf/dataset.py

Updates the `Dataset` class to allow enabling tiledb stats in write mode.

Python API for enabling/printing TileDB write statistics

---

apis/spark/src/main/java/io/tiledb/vcf/VCFInputPartitionReader.java
libtiledbvcf/src/dataset/attribute_buffer_set.cc
libtiledbvcf/src/dataset/attribute_buffer_set.h
libtiledbvcf/src/read/reader.cc

This helps to understand the size of the core C++ buffer sizes or the spark buffer sizes.

Add verbose output and logging of buffer sizes

---

apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.c
apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.h
apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.java
apis/java/src/main/java/io/tiledb/libvcfnative/VCFReader.java
apis/python/src/tiledbvcf/binding/libtiledbvcf.cc
apis/python/src/tiledbvcf/binding/reader.cc
apis/python/src/tiledbvcf/binding/reader.h
apis/python/src/tiledbvcf/dataset.py
apis/python/tests/test_tiledbvcf.py
apis/spark/src/main/java/io/tiledb/vcf/VCFDataSourceOptions.java
apis/spark/src/main/java/io/tiledb/vcf/VCFSparkSchema.java
apis/spark/src/test/java/io/tiledb/vcf/VCFDatasourceTest.java
libtiledbvcf/src/c_api/tiledbvcf.cc
libtiledbvcf/src/c_api/tiledbvcf.h
libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h
libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/read/reader.h

This is a new API to list materialized attributes. Sometimes its helpful to know the difference, and specifically in spark to allow for setting the spark schema to only materialized fields instead of all queryable fields.

Add c-api/java/spark/python api for materialized attrs

---

.azure-pipelines.yml
ci/azure-linux_mac.yml
libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake
libtiledbvcf/src/dataset/attribute_buffer_set.cc
libtiledbvcf/src/dataset/attribute_buffer_set.h
libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/read/reader.h

This add an internal threshold for double buffering of the TileDB query. If the buffers are too small, then the overhead of splitting further and running two queries is large compared to the gains. The processing of the results has been optimized greatly and is no longer a major bottleneck. Most of the time is spent in TileDB for large queries.
As a heuristic we use a size of 200MB (that would be 100MB per buffer in double buffering) as the threshold. If the buffers are smaller than this we disable double buffering and only run a single set of buffers in hope of minimizing the incomplete queries.

Add threshold for double buffering of TileDB Query

---

libtiledbvcf/src/dataset/attribute_buffer_set.cc
libtiledbvcf/src/dataset/attribute_buffer_set.h
libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/read/reader.h
libtiledbvcf/src/utils/utils.cc
libtiledbvcf/src/utils/utils.h

This changes the TileDB memory budget parameters to be set on a configuration option that is now attached to the query. TileDB 2.2.2 introduced the ability to set a config object on the query which allows certain parameters to be set more localized. This includes the `sm.memory_budget` and `sm.memory_budget_var` parameters. We now will set this to the same size as the query buffer sizes.

Automatically set the TileDB memory budget config

---

libtiledbvcf/src/dataset/attribute_buffer_set.cc
libtiledbvcf/src/dataset/attribute_buffer_set.h
libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/read/reader.h

This change makes it so that we compute the size of the tile cache as 10% of the VCF memory budget. This will limit the size of the memory usage as a user would expect. Previously the tile cache was set to 1GB or user configured, which would be mean if the user hadn't set it they might end up using more than expected memory.

Tile cache is fixed percentage of memory_budget_mb

---

apis/python/src/tiledbvcf/binding/reader.cc
apis/spark/src/main/java/io/tiledb/vcf/VCFInputPartitionReader.java

Since TileDB queries are the slowest part of reading, we should change the allocation from a 50/50 split to a 33/66 split where more memory is given to the TileDB-VCF C++ code and core TileDB library.

Split API vc C++ memory into 33/66 split

---

apis/python/setup.py
apis/python/src/tiledbvcf/binding/libtiledbvcf.cc
apis/python/src/tiledbvcf/binding/reader.cc
apis/python/src/tiledbvcf/binding/reader.h
apis/python/src/tiledbvcf/dask_functions.py
apis/python/src/tiledbvcf/dataset.py
apis/python/tests/test_tiledbvcf.py

The Dataset read() and continue_read() functions take in a return_type
parameter that allows specifying whether the results are contained in a Pandas
dataframe or Arrow table. The Dataset continue_read() function also takes in
a release_buffers parameter that indicates whether the previous results should
be freed before continuing the read.

Build Chunked Arrow Table in _read_partition()

---

libtiledbvcf/cmake/Modules/FindHTSlib_EP.cmake
libtiledbvcf/src/read/exporter.cc

For exports to vcf/vcf we should let htslib manage the info/fmt field counts. As we add the fields on export, htlib increments the account automatically. Manually override it is typically fine, except we were adding an extra count for the END field which might not always exist. The proper solution is to just stop override the field counts.

Let htslib manage info/fmt field count on export

---

libtiledbvcf/src/dataset/attribute_buffer_set.cc
libtiledbvcf/src/dataset/attribute_buffer_set.h
libtiledbvcf/src/read/reader.cc

In most cases TileDB core library will need to decompress more tiles/chunks to filter to the data requested then will be set in the
query buffers. This means than an even split is likely to cause more incomplete queries. As such, switch from a 50/50 split to a 75/25 split will yield performance improvements.
This depends on #260

Skew memory budget towards core library

---

apis/python/src/tiledbvcf/dataset.py

The Arrow export uses the VCF C API to get buffer pointers. The lifetime
of these pointers (then wrapped by arrow) is tied to the lifetime of the
Reader/Dataset. When the Reader is destructed, the buffers are freed
which can cause a crash if the buffers are later accessed. To avoid this,
we (1) call Reader::getbuffers to get handles to all of the underlying
NumPy arrays allocated in the reader. (2) attach these arrays to the
result dataframe returned by table.to_pandas. This ensures that
the buffers used by the dataframe  are not deallocated until the
dataframe itself is deallocated.
x-ref same technique in https://github.com/TileDB-Inc/TileDB-VCF/pull/198
In the future, we will refactor to transfer ownership of the NumPy
arrays directly, in order to avoid the small risk of problems that …

Fix crash in Py VCF due to buffer lifetime

---

libtiledbvcf/src/read/exporter.cc
libtiledbvcf/src/read/in_memory_exporter.cc
libtiledbvcf/src/read/reader.cc

We now check and throw a helpful exception with error details if any place (in v4 code) we attempt to lookup on a map and something isn't found. This effects header lookups and extra attribute lookups in the read algorithm.

Add proper checking for map lookups to throw useful errors

---

libtiledbvcf/src/read/reader.cc

This helps to track the TileDB query time in verbose mode.

Add query timing to verbose output

---

libtiledbvcf/src/read/reader.cc

This allows for the query buffers in C++ to free their memory when the user might hang onto the reader class. This can happen in python if the user keeps the Dataset class in the current scope. In spark there can also be a delay due to GC in cleaning up the reader. Once the TileDB-VCF query is complete it is safe to free the TileDB query buffers.

Preemptively clear buffers when read is complete

---

libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/read/reader.h

This is just an estimate based on the TileDB Query estimated result size. However it provides a decent guess to the user about how much data is left to query.

Add % of query processed in verbose output

---

libtiledbvcf/src/read/reader.cc

There is a sequence of events problem with spark calling init before setting the buffer sizes. This patch handles by always computing the memory budget breakdown for each call to the memory setter.

Always recompute the memory sizes after budget set

---

libtiledbvcf/src/read/reader.cc

When we are not double buffering we need to reset the query buffers so that the 'buffer size' as reported by the core library is the real size. This fixes an edge case when the core library is serializing the query that could cause the query buffer size to shrink each time a request was made. The problem was that the core library would send the buffer size instead of original buffer size to TileDB Cloud.
This works around the core issue but always setting the buffers. The core bug will be fixed in a pending release.

Always reset the TileDB Query buffers

---

libtiledbvcf/src/read/reader.cc

We can exit early and limit comparisons to the last query range built. The ranges are sorted on start position so we know that they are in ascending order. As such we only need to look at the last range to see if it has overlap to merge.
When there are millions of ranges this provides a large speedup in starting the query.

Limit range merge comparisons

---

apis/spark/src/main/java/io/tiledb/vcf/VCFInputPartitionReader.java

This helps in spark as we might be able to free unused heap memory faster.

Add GC hint that there is items to garbage collect

---

apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.c
apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.h
apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.java
apis/java/src/main/java/io/tiledb/libvcfnative/VCFReader.java
apis/python/src/tiledbvcf/binding/libtiledbvcf.cc
apis/python/src/tiledbvcf/binding/reader.cc
apis/python/src/tiledbvcf/binding/reader.h
apis/python/src/tiledbvcf/dataset.py
apis/spark/src/main/java/io/tiledb/vcf/VCFDataSourceOptions.java
apis/spark/src/main/java/io/tiledb/vcf/VCFInputPartitionReader.java
libtiledbvcf/src/c_api/tiledbvcf.cc
libtiledbvcf/src/c_api/tiledbvcf.h
libtiledbvcf/src/cli/tiledbvcf.cc
libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/read/reader.h

Add tile cache/buffer size percentage setters for c-api, python and spark

Add tile cache/buffer size percentage setters

---

apis/python/src/tiledbvcf/binding/libtiledbvcf.cc
apis/python/src/tiledbvcf/binding/reader.cc
apis/python/src/tiledbvcf/binding/reader.h
apis/python/src/tiledbvcf/dataset.py
libtiledbvcf/src/c_api/tiledbvcf.cc
libtiledbvcf/src/c_api/tiledbvcf.h
libtiledbvcf/src/cli/tiledbvcf.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h
libtiledbvcf/src/read/in_memory_exporter.cc
libtiledbvcf/src/read/in_memory_exporter.h
libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/read/reader.h
libtiledbvcf/src/utils/rwlock.h
libtiledbvcf/src/utils/unique_rwlock.h
libtiledbvcf/test/src/unit-c-api-writer.cc
libtiledbvcf/test/src/unit-vcf-store.cc

This PR adjust the number of times we query the VCF header array. We now attempt to lazily load information and to use header data from the running VCF query instead of data from the underlying array. Lastly we no longer user est_result_size for the vcf array querying and instead use a % of the read query's memory budget.

Optimizations for VCF Header Array Querying

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h
libtiledbvcf/src/read/bcf_exporter.cc
libtiledbvcf/src/read/exporter.cc
libtiledbvcf/src/read/exporter.h
libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/read/reader.h
libtiledbvcf/src/read/tsv_exporter.cc

We now only fetch headers for TSV or VCF exports or in-memory when exporting a fmt/info field which is not materialized.

Only fetch headers if needed in export

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h
libtiledbvcf/src/read/bcf_exporter.cc
libtiledbvcf/src/read/bcf_exporter.h
libtiledbvcf/src/read/reader.cc
libtiledbvcf/test/src/unit-c-api-reader.cc
libtiledbvcf/test/src/unit-vcf-store.cc

If the user is exporting all samples, we can avoid actually getting the full list of samples names in most cases. This removes a query to the vcf_header array.
Depends on #285

 Avoid unnecessary fetching of sample list for v4

---

apis/python/src/tiledbvcf/binding/libtiledbvcf.cc
apis/python/src/tiledbvcf/binding/reader.cc
apis/python/src/tiledbvcf/binding/reader.h
apis/python/src/tiledbvcf/dask_functions.py
apis/python/src/tiledbvcf/dataset.py

This change reworks the python api to build arrow buffers and array table directly. Previously it used numpy arrays and then used the `libtiledbvcf` arrow functionality to build the arrow table. The problem we've been encountering is that the arrow table did not own the underlying buffers. This meant that when the python `Dataset` class went out of scope and was GC'ed the underlying numpy arrays were gc'ed. This leads to segfaults as the arrow table referenced no-longer-existing data.

Switch python API to build and own arrow table and buffers

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h

This moved building of materialized attributes into its own function that will avoid needing to fetch the VCF header fmt/info fields.

Improve materialized attribute detection

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h
libtiledbvcf/src/read/reader.cc

This avoid an issue in the core library with REST arrays and reducing buffer sizes. This is harmless for all arrays and has no practical effect in most cases, but avoids a bug in one set of circumstances.

Always reset metadata array buffers on reads

---

apis/python/.gitignore
apis/python/src/tiledbvcf/binding/reader.h

Remove unused variable in pybind11, this fixes a warning from CI.

Remove unused variable in pybind11

---

apis/python/src/tiledbvcf/dataset.py

This solves a problem were some options are not properly printed out when verbose is enabled because the verbose mode has not been set.

Verbose mode should be set first in Python

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h
libtiledbvcf/src/read/reader.cc

Tile cache and the TileDB `sm.memory_budget` and `sm.memory_budget_var` parameters are not effective with TileDB Cloud arrays since all computations happen in the remote server.

TileDB Cloud Arrays should use memory for buffers

---

libtiledbvcf/src/dataset/attribute_buffer_set.cc
libtiledbvcf/src/dataset/attribute_buffer_set.h
libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h
libtiledbvcf/src/read/reader.cc

This adjusts the TileDB query buffers sizes based on datatypes. This allows us to better allocated the buffers by reducing the size of smaller datatypes so that we attempt to have a more equal element count and not leave some buffers over half empty.

Add hueristic to size query buffers

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/test/src/unit-c-api-reader.cc

If the user requested all samples for reading but then used partitioning we want to just fetch headers based on the list of samples instead of the min/max from the non-empty-domain.

Handle sample partitioning with fetch_header

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h

The core TileDB library caches the non-empty-domain after the first load. This change takes advantage of that by fetching the
non-empty-domain on an async thread allowing for loading the non-empty-domain before it is needed in the read path. This will save up to a few seconds from reads.

Load non-empty-domain in background

---

apis/python/setup.py

Fix for issue building the Python API without conda (see #305) by creating unversioned symlinks to pyarrow libraries.

Symlink unversioned pyarrow libraries to build wheels

---

ci/azure-linux_mac.yml
ci/native_libs-linux_osx.yml
docker/Dockerfile-cli
libtiledbvcf/cmake/Modules/FindHTSlib_EP.cmake
libtiledbvcf/cmake/patches/htslib-1.10-config.patch

from and details in: https://github.com/samtools/htslib/pull/1198

Patch htslib 1.10 to fix build with autoconf 2.70+

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/read/reader.cc

There is a new configuration parameter in the core library which will skip using the estimated result size for partitioning. For VCF this is important because there often can be a large number of ranges on each query and this results in performance degradation due to the time it takes to compute the estimated result sizes.

Set core sm.skip_est_size_partitioning config to 'true' by default

---

libtiledbvcf/src/dataset/attribute_buffer_set.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h

The `attribute_is_fixed_len` function previously was returning fixed length for `sample` even for v4 arrays because the name is the same between v2/v3 and v4. This adjusts this to check for v2/v3 cases.
This only effected the buffer size building, and caused us to be off by missing 1 set of offsets in the calculations for max sizes we could use.

Fix attribute_is_fixed_len for v4 sample

---

libtiledbvcf/test/src/unit-c-api-reader.cc

This fixes the test to check all returned values, instead of only the first one.

Fix C API: Reader submit (partitioned)

---

libtiledbvcf/src/utils/utils.cc
libtiledbvcf/src/utils/utils.h
libtiledbvcf/test/run-cli-tests.sh

There was a bug in the logic of partitioning in that we used ceil not floor when computing the number of element per partition. This meant that if we rounded up and used up all the elements before the requested user partitioning count we would run out of samples/regions and end up with empty partitions. The empty partitions were not handled gracefully and caused the library to incorrectly fetch all headers. Depending on the exact scenario it might have also resulted in a segfault when attempting to set empty ranges on the core library due to accessing non-existent vector elements.
The fix for this issue is to use floor when computing element per partition and to just assign the left overs to the first N partitions,
where one is given to each partition until we run out of "left over" …

Fix partitioning logic for uneven division

---

apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.c
apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.h
apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.java
apis/java/src/main/java/io/tiledb/libvcfnative/VCFReader.java
apis/python/src/tiledbvcf/binding/libtiledbvcf.cc
apis/python/src/tiledbvcf/binding/reader.cc
apis/python/src/tiledbvcf/binding/reader.h
apis/python/src/tiledbvcf/dataset.py
apis/spark/src/main/java/io/tiledb/vcf/VCFDataSourceOptions.java
apis/spark/src/main/java/io/tiledb/vcf/VCFInputPartitionReader.java
libtiledbvcf/src/c_api/tiledbvcf.cc
libtiledbvcf/src/c_api/tiledbvcf.h
libtiledbvcf/src/cli/tiledbvcf.cc
libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/read/reader.h

Progress estimation relies on estimated result size which can have a performance and memory impact in some scenarios. This lets users use verbose mode but skip the impact if they don't require the progress update.

Support disabling progress estimation w/verbose

---

apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.java
apis/java/src/main/java/io/tiledb/libvcfnative/NativeLibLoader.java

This prints only after all libs are loaded from the jar, to ensure it will be successful.

Adjust where Java verion info is printed

---

apis/python/tests/test_tiledbvcf.py
apis/spark/src/main/java/io/tiledb/vcf/VCFSparkSchema.java
apis/spark/src/test/java/io/tiledb/vcf/VCFDatasourceTest.java
libtiledbvcf/src/cli/tiledbvcf.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/read/in_memory_exporter.cc
libtiledbvcf/src/read/in_memory_exporter.h
libtiledbvcf/src/read/tsv_exporter.cc
libtiledbvcf/src/vcf/region.cc
libtiledbvcf/src/vcf/region.h
libtiledbvcf/test/src/unit-c-api-reader.cc
libtiledbvcf/test/src/unit-helpers.h

Some users would like to know not just the matching range start/end but the row number of the bed file. This adds support for the new field of `Q:LINE` or `query_bed_line`/`queryBedLine`.

Add support for query bed file line number export

---

libtiledbvcf/src/read/reader.cc

Sample partitions should never be empty after [#318](https://github.com/TileDB-Inc/TileDB-VCF/pull/318). However incase it is, this safety check will exit early instead of running over the entire dataset.

If a sample partition is empty exit early

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h

This introduces a new rwlock and thread TileDBVCFDataset attribute to handle race conditions when destroying the dataset class. If the preloading of the non empty domains had not completed by the time the destructor was called this could cause a segfault.
Similarly we now also grab read locks of the data array or vcf header array rwlock in order to block the destructor if another thread was making use of the array objects. No where in the c++ code do we currently access in parallel to destruction, however in order to be thread-safe in the c-api this is needed.

Fix concurrent issues with dataset destructor

---

ci/native_libs-linux_osx.yml

No need to run tests when building libs for jars

No need to run tests when building libs for jars

---

apis/spark/src/main/java/io/tiledb/vcf/VCFDataSourceOptions.java
apis/spark/src/main/java/io/tiledb/vcf/VCFDataSourceReader.java
apis/spark/src/test/java/io/tiledb/vcf/VCFDatasourceTest.java

This allows the user to set a single partition or partition index for ranges/samples like is supported in other APIs. This is helpful when debugging.

Add spark option to setting specific partition idx

---

apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.c
apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.h
apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.java
apis/java/src/main/java/io/tiledb/libvcfnative/VCFReader.java
apis/python/src/tiledbvcf/binding/libtiledbvcf.cc
apis/python/src/tiledbvcf/binding/reader.cc
apis/python/src/tiledbvcf/binding/reader.h
apis/spark/src/main/java/io/tiledb/vcf/VCFDataSourceOptions.java
apis/spark/src/main/java/io/tiledb/vcf/VCFInputPartitionReader.java
apis/spark/src/test/java/io/tiledb/vcf/VCFDatasourceTest.java
libtiledbvcf/src/c_api/tiledbvcf.cc
libtiledbvcf/src/c_api/tiledbvcf.h
libtiledbvcf/src/cli/tiledbvcf.cc
libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/read/reader.h

This adds three new reader options for printing the read details including the sample list used, the vcf regions passed and the actual TileDB query ranges performed.
Three new CLI options are added:
```
--debug-print-vcf-regions
Enable debug printing of vcf region passed by user or bed file. Requires verbose mode
--debug-print-sample-list
Enable debug printing of sample list used in read. Requires verbose mode
--debug-print-tiledb-query-ranges
Enable debug printing of tiledb query ranges used in read. Requires verbose mode
```
Three spark options where added:
`debug.print_vcf_regions`
`debug.print_sample_list`
`debug.print_tiledb_query_ranges`
Python is implemented in pybind11 but the user interface is not defined yet. This will be a followup with change to how we can more easily pass all …

Add debugging options for printing query details

---

apis/python/src/tiledbvcf/binding/libtiledbvcf.cc
apis/python/src/tiledbvcf/binding/writer.cc
apis/python/src/tiledbvcf/binding/writer.h
apis/python/src/tiledbvcf/dataset.py
apis/python/tests/test_tiledbvcf.py
libtiledbvcf/src/c_api/tiledbvcf.cc
libtiledbvcf/src/c_api/tiledbvcf.h
libtiledbvcf/src/cli/tiledbvcf.cc
libtiledbvcf/src/utils/utils.cc
libtiledbvcf/src/utils/utils.h
libtiledbvcf/src/write/writer.cc
libtiledbvcf/src/write/writer.h
libtiledbvcf/test/src/unit-vcf-export.cc
libtiledbvcf/test/src/unit-vcf-store.cc

This is a (large) performance optimization in cases where the samples have a large number of pseudo configs which are small. These small contigs create a large number of fragments which can cause slower listing of the array on S3/GCS/Azure Blob Store object stores. This makes opening the array take significantly longer in certain scenarios. The change here allows the user to set two list (keep separate and mergeable) of contigs which are allowed to be merged into a single fragment in the sample batch.
The default `keep-as-separate` list will keep human contigs in USCS or ensembl format from being merged. For performance of reads, it is desirable to keep contigs which are going to read frequently or are large in size separate and not merged.
Further merge takes into account (automatically) …

Support for merging contigs into single fragments

---

libtiledbvcf/src/read/reader.cc

This solves an undefined behavior of calling get if the std::future is no longer valid.

Check async query future is valid before getting

---

libtiledbvcf/src/read/tsv_exporter.cc
libtiledbvcf/test/run-cli-tests.sh

Remove duplicate `SAMPLE` column name in TSV export when `SAMPLE` is specified in the `--tsv-fields`.

Remove duplicate sample field in TSV header

---

libtiledbvcf/src/read/tsv_exporter.cc
libtiledbvcf/test/run-cli-tests.sh

Remove extra tab in records of TSV export when SAMPLE is specified in the --tsv-fields. Improved the test to cover this case.

Remove extra tab in TSV export

---

ci/azure-linux_mac.yml

Update CI script to run `pylint` on all directories with an `__init__.py` file.

Update pylint CI script

---

docker/Dockerfile-py

Bumps the miniconda3 image used by tiledbvcf-py to 4.10.3.

Update miniconda3 image

---

libtiledbvcf/cmake/Modules/FindSpdlog_EP.cmake
libtiledbvcf/src/utils/logger.cc
libtiledbvcf/src/utils/logger.h
libtiledbvcf/src/utils/logger_public.h

* Update `spdlog` cmake file so the `ep_tiledb` dependency is conditional.
* Remove nested namespaces, which are a C++17 extension.

Fix spdlog cmake and remove nested namespaces

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h
libtiledbvcf/test/src/unit-vcf-utils.cc

In the `TileDBVCFDataset::vacuum*array*` functions, an array can be closed while other threads (like preloading) are still using the array.
Avoid a race condition with the same lock and join sequence used to delete the arrays in `~TileDBVCFDataset`.

Block until safe to close arrays in vacuum operations

---

libtiledbvcf/src/read/reader.cc
libtiledbvcf/test/run-cli-tests.sh

* Update when `finalize_export` is called for v4 arrays to avoid incomplete VCF exports. 
* Remove unused `verbose` variable to resolve CI build issue.

Fix incomplete VCF export for v4 arrays

---

apis/spark/src/test/java/io/tiledb/vcf/VCFDatasourceTest.java
libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/utils/logger.cc
libtiledbvcf/src/utils/logger.h
libtiledbvcf/src/utils/logger_public.h
libtiledbvcf/test/CMakeLists.txt
libtiledbvcf/test/src/unit-vcf-time-travel.cc

Add support for time traveling reads. The start and/or end timestamp of the read operation can be specified with the `tiledb-config` parameters: `vcf.start_timestamp` and `vcf.end_timestamp`.
```shell
$ start=$(date -d 2021/8/1 +%s000)
$ end=$(date -d 2021/8/7 +%s000)
$ tiledbvcf export --uri small_dataset \
--regions 1:1-50000,2:1-50000,3:1-50000 \
--sample-names G1,G2,G3 \
--output-dir data/exported-subsets \
--tiledb-config "vcf.start_timestamp=$start,vcf.end_timestamp=$end" \
--log-level INFO
[2021-08-16 16:13:52.717] [tiledb-vcf] [Process: 262730] [Thread: 262730] [info] Using vcf.start_timestamp from config: 1627790400000
[2021-08-16 16:13:52.717] [tiledb-vcf] [Process: 262730] [Thread: 262730] [info] Using vcf.end_timestamp from config: 1628308800000
[2021-08-16 16:13:52.719] …
```

Add support for time traveling

---

libtiledbvcf/src/vcf/region.cc

Increase bedfile region parsing timeout to 5 minutes. We've seen timeouts when people have large (30+ million region) bed files.

Increase bedfile region parsing timeout to 5 minutes

---

libtiledbvcf/src/read/reader.cc

Truly avoid memory budget setting for TileDB Cloud Arrays. Previously we set it to a small value which since TileDB 2.3 was set on the query config (not just the context). The query config is shipped with the serialized query object, causing abysmal performance.

Truly avoid memory budget setting for TileDB Cloud Arrays

---

libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/read/reader.h

The double buffering is not worth it. The processing time in TileDB-VCF is always a fraction of the time spent in TileDB. Its better to use larger query buffers for TileDB then to half them for double buffering.

Remove double buffering

---

apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.c
apis/java/src/main/java/io/tiledb/libvcfnative/VCFBedFile.java
apis/spark/build.gradle
apis/spark/src/main/java/io/tiledb/vcf/VCFDataSourceReader.java
apis/spark/src/main/java/io/tiledb/vcf/VCFSparkSchema.java
apis/spark/src/test/java/io/tiledb/vcf/VCFDatasourceTest.java
apis/spark/src/test/resources/E001_15_coreMarks_dense.bed.gz
apis/spark/src/test/resources/E001_15_coreMarks_dense.bed.gz.tbi
libtiledbvcf/src/read/in_memory_exporter.cc
libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/vcf/region.cc
libtiledbvcf/src/vcf/region.h
libtiledbvcf/test/src/unit-c-api-reader.cc

Implement queries of BED file line numbers in the new Spark partitioning method.
The `Region` class was refactored:
* All regions objects are always "0-indexed, inclusive" (this was already true).
* Simplify the logic for creating a region object by removing the `Region::Type`.
* Always maintain a "0-indexed, inclusive" string representation of the region in the `region_str` field.
* Add the line number field to the `region_str` field to preserve line number information as the region string is passed back and forth between `C` and `Java`.
* Handle "1-indexed, inclusive" regions and "0-indexed, inclusive" regions in the `Region::Region(str)` constructor, which is required by the new Spark partitioning method.
More documentation on the `Region` class changes can be found in …

BED file line number handling

---

.azure-pipelines.yml
ci/build-images.yml
docker/Dockerfile-cli

This addresses an issue with the CLI Docker image reported in #370 by @Alexander-Stuckey and incorporates his suggested fix (thanks, Alexander!). We've also added a CI step to validate the images after they're built.

Add libcurl to the CLI's final image

---

.azure-pipelines.yml

This solves a linker problem due to TileDB prebuilt using newer glibc linkage.

Update native build to Ubuntu 20.04 for releases

---

.gitignore
libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h
libtiledbvcf/src/utils/utils.h
libtiledbvcf/src/vcf/region.cc
libtiledbvcf/src/write/writer.cc

Some threads are using raw `std::thread` and we potentially miss exceptions thrown by these threads.
Update all threads to launch with `std::async` and capture the `std::future`:
```c++
std::future<...> thr1 = std::async(std::launch::async, ...);
```
Wrap the future's `.get()` statement in a try/catch block to catch exceptions from the thread:
```c++
try {
thr1.get();
} catch(...) {
// error handling code
}
```
Add `TRY_CATCH_THROW` in `utils.h` as a helper and wrap all thread related function calls so we catch, log, and re-throw any exceptions.

Update std::thread to std::async and add threading try/catch blocks

---

libtiledbvcf/cmake/Modules/FindCatch_EP.cmake
libtiledbvcf/src/cli/tiledbvcf.cc
libtiledbvcf/src/read/tsv_exporter.cc
libtiledbvcf/src/read/tsv_exporter.h
libtiledbvcf/test/run-cli-tests.sh

Change the TSV export prefix for `FORMAT` fields from `S:`  to `F:`.
[sc-11687]

Change TSV export prefix for FORMAT fields

---

libtiledbvcf/src/write/writer.cc
libtiledbvcf/src/write/writer_worker.h
libtiledbvcf/src/write/writer_worker_v2.cc
libtiledbvcf/src/write/writer_worker_v3.cc
libtiledbvcf/src/write/writer_worker_v4.cc

Fix issue where setting the ingestion legacy option `--mem-budget-mb` to a value >4GB resulted in 0 records being ingested.

Fix issue with legacy ingestion option

---

apis/java/src/main/java/io/tiledb/libvcfnative/VCFReader.java

Currently, Spark generates an error when opening a dataset created with materialized fmt/info attributes that are not present in the ingested VCF data. This PR converts the error to a warning.

Spark warning if create time attribute does not exist in VCF headers

---

apis/python/src/tiledbvcf/dataset.py
libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/write/writer.cc

* Enable `log-level=debug` when the `verbose` option is set in python.
* Catch errors from arrow and return an empty Table
[sc12783]

Enable verbose logging and catch arrow errors in python API

---

libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/write/writer.cc

The `verbose` argument is currently ignored by the Python API and presumably others.

Fix verbose toggle for APIs

---

libtiledbvcf/src/dataset/attribute_buffer_set.cc

The `default` case in the `switch` statement fixes an issue introduced with TileDB 2.7.

Add default case to switch statement

---

libtiledbvcf/src/cli/tiledbvcf.cc
libtiledbvcf/src/write/writer.cc
libtiledbvcf/src/write/writer.h

Add an option to ingest chromosomes and pseudo-contigs separately. Since pseudo-contigs are smaller, they can be ingested in larger batches, which reduces the total fragment count.
The new option for `tiledbvcf store`:
* `--contig-mode all` : Default. Ingest all contigs, no change in existing behavior.
* `--contig-mode separate`: Ingest contigs in the `contigs-to-keep-separate` list, human chromosomes by default.
* `--contig-mode merged`: Ingest contigs not in the `contigs-to-keep-separate` list and merge them into fragments that do not overlap the human chromosomes.
[sc-14684]

Add option to ingest chromosomes and pseudo-contigs separately

---

ci/native_libs-linux_osx.yml
libtiledbvcf/src/read/reader.cc

Before TileDB 2.5, an incomplete query that returned 0 results was an error condition and TileDB-VCF threw an error. In TileDB 2.5 - 2.6, an incomplete query that returns 0 results is a normal condition, so this PR removes the TileDB-VCF error.
This PR also includes a small change to add missing native libraries to the Spark jar file.
[sc-15261]
[sc-15262]

Remove error when an incomplete query has 0 results

---

apis/java/src/main/java/io/tiledb/libvcfnative/VCFReader.java
apis/python/src/tiledbvcf/binding/reader.cc

There are cases where users have a lot of fields and are selecting only a handful of records. For those we shouldn't block on needing 10MB per field.

Remove lower bound limit for buffer sizes

---

libtiledbvcf/src/cli/tiledbvcf.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h
libtiledbvcf/test/src/unit-vcf-utils.cc

Add capability to consolidate and vacuum commits, which is a new feature in TileDB 2.8.

Consolidate and vacuum commits

---

libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake
libtiledbvcf/src/write/record_heap_v4.cc
libtiledbvcf/src/write/record_heap_v4.h
libtiledbvcf/src/write/writer.cc
libtiledbvcf/src/write/writer.h
libtiledbvcf/src/write/writer_worker.h
libtiledbvcf/src/write/writer_worker_v4.cc
libtiledbvcf/src/write/writer_worker_v4.h
libtiledbvcf/test/src/unit-vcf-export.cc
libtiledbvcf/test/src/unit-vcf-store.cc

This PR moves anchor records for each contig (or combined contig) into a separate TileDB fragment. This change avoids an edge case where anchor records could violate the global sort order.

Fix global order of anchors at region boundaries

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc

This PR disables preloading of non-empty domains, which resolves intermittent segfaults seen when opening large VCF datasets on s3.

Disable non-empty domain preload

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/variant_stats.cc
libtiledbvcf/src/dataset/variant_stats.h

Consolidate variant stats array commits and fragment metadata as part of the dataset consolidate commands.
Also closes [sc-15164]

Consolidate variant stats array commits and fragment metadata

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h
libtiledbvcf/src/dataset/variant_stats.cc
libtiledbvcf/src/dataset/variant_stats.h
libtiledbvcf/test/src/unit-vcf-store.cc

Add support for the new group API in TileDB 2.8.
Example usage with TileDB Cloud and S3:
1. Register a new VCF dataset group with TileDB Cloud:
```
tiledbvcf create -u tiledb://<NAMESPACE>/s3://<BUCKET>/<PREFIX> ...
```
2. Ingest samples to S3 storage:
```
tiledbvcf store -u s3://<BUCKET>/<PREFIX> ...
```
3. Query the VCF dataset group in TileDB Cloud:
```
tiledbvcf export -u tiledb://<NAMESPACE>/<GROUP> ...
```

Add support for the new TileDB group API

---

libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake
libtiledbvcf/src/vcf/vcf_merger.cc

* Silence unused variable warning
* Bump TileDB version to 2.9.5

Silence unused variable warning and bump TileDB version

---

apis/java/build.gradle
apis/spark/build.gradle
apis/spark3/build.gradle
libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

This bumps the TileDB dependency to 2.10.1.

Upgrade TileDB-VCF to 2.10

---

apis/python/conda-env.yml
apis/python/tests/test_tiledbvcf.py
libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake
libtiledbvcf/src/dataset/variant_stats.cc
libtiledbvcf/src/dataset/variant_stats.h
scripts/update-tiledb-version.py

This PR fixes a data dependent global order violation when writing the new `variant_stats` array. The `allele` dimension is moved from a dimension to an attribute in the `variant_stats` schema.

Fix global order violation

---

apis/python/src/tiledbvcf/binding/libtiledbvcf.cc
apis/python/src/tiledbvcf/binding/writer.cc
apis/python/src/tiledbvcf/binding/writer.h
apis/python/src/tiledbvcf/dataset.py
apis/python/tests/test_tiledbvcf.py
apis/spark/src/main/java/io/tiledb/vcf/VCFInputPartitionReader.java
apis/spark3/src/main/java/io/tiledb/vcf/VCFPartitionReader.java
libtiledbvcf/src/CMakeLists.txt
libtiledbvcf/src/c_api/tiledbvcf.cc
libtiledbvcf/src/c_api/tiledbvcf.h
libtiledbvcf/src/cli/tiledbvcf.cc
libtiledbvcf/src/dataset/allele_count.cc
libtiledbvcf/src/dataset/allele_count.h
libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h
libtiledbvcf/src/dataset/variant_stats.cc
libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/write/writer.cc
libtiledbvcf/src/write/writer.h
libtiledbvcf/src/write/writer_worker.h
libtiledbvcf/src/write/writer_worker_v4.cc
libtiledbvcf/src/write/writer_worker_v4.h
libtiledbvcf/test/run-cli-tests.sh

This PR adds optional ingestion tasks to efficiently compute allele count and allele frequency. 
Ingestion tasks create arrays containing useful statistics at ingestion time. This approach is very efficient because ingestion is already reading every VCF record.
**NOTE:** The ingestion task must be enabled at array creation time.
**Python**
```python
ds = tiledbvcf.Dataset(uri, mode="w")
ds.create_dataset(enable_allele_count=True, enable_variant_stats=True)
```
**CLI**
```bash
tiledbvcf create -u vcf.tdb --enable-allele-count --enable-variant-stats
```
Ingestion task overview:
* The `allele_count` task creates an array of called allele counts, for example:
```
pos                    ref                                                alt filter   gt  count
0    5041703 …
```

Add optional ingestion tasks

---

libtiledbvcf/cmake/Modules/FindCatch_EP.cmake
libtiledbvcf/cmake/Superbuild.cmake
libtiledbvcf/test/CMakeLists.txt

This is an alternative to PR #445, porting the FindCatch_EP.cmake file from core, with one modification. I'm looking into why this is necessary in VCF but not in core: https://github.com/TileDB-Inc/TileDB-VCF/blob/awenocur/sc-19637/port-catch-search/libtiledbvcf/cmake/Modules/FindCatch_EP.cmake#L72

port FindCatch_EP from core

---

apis/java/build.gradle
apis/spark/build.gradle
apis/spark3/build.gradle
libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

Bump the TileDB dependency to 2.10.3.

Update TileDB and java/spark for version 0.18.0

---

apis/java/build.gradle
apis/spark/build.gradle
apis/spark3/build.gradle
libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake
libtiledbvcf/src/dataset/allele_count.cc
libtiledbvcf/src/dataset/allele_count.h
libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h
libtiledbvcf/src/dataset/variant_stats.cc
libtiledbvcf/src/dataset/variant_stats.h

Story details: https://app.shortcut.com/tiledb-inc/story/20180

chore: [sc-20180] Upgrade TileDB-VCF to TileDB 2.11

---

libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake
libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h
libtiledbvcf/src/write/writer.cc

The resume ingestion logic was changed in #434 to check for an overlap between sample names in the batch being ingested and sample names in existing fragments. This approach does not work when sample names are not sorted.
This PR checks for an exact match between the ingested batch's sample range and the sample range of all existing fragments. If a match is found, and the contig is contained in an existing fragment for the sample range, the contig is skipped.

Check for an exact sample range match when resuming ingestion

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc

`vfs:` should be prepended to remote URIs that are interrogated for any samples. It appears that reading the samples themselves is currently handled properly.

Wrap URIs with VFS scheme as necessary

---

.azure-pipelines.yml
apis/java/build.gradle
apis/spark/build.gradle
apis/spark3/build.gradle
libtiledbvcf/src/dataset/tiledbvcfdataset.cc

Initialize VFS plugin for htslib in dataset create path, so we can read VCF attributes from a VCF file that needs additional access rights.

Initialize VFS plugin for htslib in dataset create path

---

apis/python/tests/test_tiledbvcf.py

After upgrading to TileDB 2.12.0, a python test relying on TileDB-Py fails because TileDB-Py is using an older version of TileDB.

Skip test using conflicting version of TileDB

---

.azure-pipelines.yml
.github/workflows/backport.yml
apis/python/tests/test_tiledbvcf.py
libtiledbvcf/src/dataset/allele_count.cc
libtiledbvcf/src/dataset/allele_count.h
libtiledbvcf/src/dataset/variant_stats.cc
libtiledbvcf/src/dataset/variant_stats.h

Create a new query after each finalize call instead of reusing the query in the `variant_stats` and `allele_count` ingestion tasks.

Create new query after finalize in stats ingestion tasks

---

libtiledbvcf/src/cli/tiledbvcf.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h

Provide a `tiledbvcf create` option to use dictionary + zstd compression on the sample dimension, instead of dictionary encoding only. This option improves the compression ratio.
```
--compress-sample-dim                 Add zstd compression to the sample dimension.
```

Add zstd compression to the sample dimension

---

Makefile
libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/read/reader.h
libtiledbvcf/src/stats/variant_stats_reader.cc
libtiledbvcf/src/stats/variant_stats_reader.h

* Reduce memory usage when fetching the one VCF header.
* Enable async mode for AF filtering to allow the variant stats query to run in parallel with the VCF data query.
* Add developer convenience `Makefile` for common commands

Memory usage and latency improvements

---

apis/python/src/tiledbvcf/binding/libtiledbvcf.cc
apis/python/src/tiledbvcf/binding/reader.cc

Release the python GIL, to allow other python threads to run while libtiledbvcf is reading/writing TileDB arrays.

Release python GIL

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/test/src/unit-vcf-export.cc
libtiledbvcf/test/src/unit-vcf-store.cc

* Revert recent changes to `fetch_vcf_headers_v4`, which caused an issue with reading annotation VCFs.
* Add unit tests to read annotation VCFs.

Revert changes to fetch_vcf_headers_v4

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc

change to use preprocessor '&&' operator as 'and' is incorrectly handled by some msvc versions

change to use preprocessor '&&' operator

---

libtiledbvcf/src/stats/allele_count.cc
libtiledbvcf/src/stats/variant_stats.cc
libtiledbvcf/test/inputs/stats/first.vcf
libtiledbvcf/test/run-cli-tests.sh

During stats ingestion, handle the case where one allele is missing, for example GT=".|1" or GT="1|.".

Handle one missing allele in stats arrays

---

.github/workflows/windows.yml
apis/python/setup.py
apis/python/src/tiledbvcf/__init__.py
apis/python/tests/test_tiledbvcf.py
ci/build-libtiledbvcf.bat
ci/build-tiledbvcf-py.bat
ci/gha-win-env.yml
libtiledbvcf/src/CMakeLists.txt

This is a follow-up to PR #484 from @dhoke4tdb. That merged PR enabled building libtiledbvcf on Windows by linking against a customized build of htslib on msys2. The goal of this PR is to enable building the Python package on Windows as well.
Current status: Python client builds on Windows, tests pass ([link to passing build on my fork](https://github.com/jdblischak/TileDB-VCF/actions/runs/4439652394/jobs/7792414141))
* Install [Build Tools for Visual Studio 2019 (version 16.9)](https://my.visualstudio.com/Downloads)
* Install conda/mamba (I recommend [Mambaforge](https://github.com/conda-forge/miniforge#mambaforge))
* Open Mambaforge Prompt (assuming you followed the installer advice to not add conda to PATH, you need to use the app to properly activate conda in the shell)
* Checkout my …

Build tiledbvcf-py on Windows

---

apis/python/src/tiledbvcf/binding/libtiledbvcf.cc
apis/python/src/tiledbvcf/binding/writer.cc
apis/python/src/tiledbvcf/binding/writer.h
apis/python/src/tiledbvcf/dataset.py
apis/python/tests/test_tiledbvcf.py
ci/azure-linux_mac.yml
ci/run-clang-format.sh
libtiledbvcf/src/c_api/tiledbvcf.cc
libtiledbvcf/src/c_api/tiledbvcf.h
libtiledbvcf/src/cli/tiledbvcf.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h
libtiledbvcf/src/read/delete_exporter.cc
libtiledbvcf/src/read/delete_exporter.h
libtiledbvcf/src/stats/allele_count.cc
libtiledbvcf/src/stats/allele_count.h
libtiledbvcf/src/stats/variant_stats.cc
libtiledbvcf/src/stats/variant_stats.h
libtiledbvcf/src/write/writer.cc
libtiledbvcf/src/write/writer.h
libtiledbvcf/src/write/writer_worker.h
libtiledbvcf/src/write/writer_worker_v4.cc
libtiledbvcf/src/write/writer_worker_v4.h
libtiledbvcf/test/run-cli-tests.sh
libtiledbvcf/test/src/unit-vcf-iter.cc

Update dataset creation to enable the following by default:
* Creation of the `allele_count` array.
* Creation of the `variant_stats` array.
* Zstd compression of the dictionary encoded sample dimension.
These options can be disabled from the CLI and python API.
The internal API for flush/finalize of the stats arrays was refactored, based on edge cases exposed in CI by always enabling these arrays.
[sc-11702]
[sc-28384]

Update dataset creation defaults

---

_quarto.yml
apis/python/src/tiledbvcf/dataset.py
apis/python/tests/test_tiledbvcf.py

* Update some default values in the python API to match the defaults in C++, so we get the desired defaults.
* Add convenience arg `tiledb_config` to `Dataset` to allow passing a TileDB config without creating a `ReadConfig` object.
* Minor comment updates and code refactoring.
* Fix the doc landing page.

Minor updates to python API

---

apis/python/src/tiledbvcf/__init__.py
apis/python/src/tiledbvcf/allele_frequency.py

Add `read_allele_frequency` to read and compute allele frequency from the variant stats array.
Example:
```python
import tiledbvcf
dataset_uri = "VCF_DATASET_URI"
region = "1:840000-850000"
df = tiledbvcf.read_allele_frequency(dataset_uri, region)
pos                                             allele      ac      an   af
0  840035                                                  T  200000  200000  1.0
1  842056                                                  A  200000  200000  1.0
2  843214                                                  C  100000  200000  0.5
3  843214                  CCTGCCCGGTCCTTCTGACCAGCCGAGAGAGTA  100000  200000  0.5
4  844297                                                  A  200000  200000  1.0
5  844297  ACCGGGTCAGGCCCCCCGGGCGCACCGTTGCTGGTATATGCGGTGA... …
```

Add read_allele_frequency to python API

---

ci/azure-linux_mac.yml
libtiledbvcf/src/write/writer.cc

During ingestion, finalize the stats arrays so each fragment contains data from one chromosome or data from a set of pseudo contigs.
Add `mamba` to speed up python CI.

Finalize stats arrays to optimize fragment layout

---

libtiledbvcf/src/stats/allele_count.cc
libtiledbvcf/src/stats/variant_stats.cc
libtiledbvcf/test/inputs/stats/first.vcf

During VCF ingestion, validate that GT is in the range of the provided ALT alleles when updating the stats arrays.

Validate GT value in stats ingestion

---

documentation/index.md

The introductory documentation has a link in the 'Quick Start' section which comes up as the actual `README.md` markdown, as opposed to the rendered page. Compare
- current https://tiledb-inc.github.io/TileDB-VCF/documentation/docker/README.md
- proposed https://tiledb-inc.github.io/TileDB-VCF/documentation/docker/
The PR just removes the trailing README.md.

Remove trailing README.md from link to obtain rendered page

---

apis/python/src/tiledbvcf/binding/libtiledbvcf.cc
apis/python/src/tiledbvcf/binding/writer.cc
apis/python/src/tiledbvcf/binding/writer.h
apis/python/src/tiledbvcf/dataset.py
apis/python/tests/test_tiledbvcf.py
libtiledbvcf/src/c_api/tiledbvcf.cc
libtiledbvcf/src/c_api/tiledbvcf.h
libtiledbvcf/src/cli/tiledbvcf.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h
libtiledbvcf/src/write/writer.cc
libtiledbvcf/src/write/writer.h

Add CLI and python API option to set the zstd compression level when creating the VCF dataset.

Set the zstd compression level when creating the VCF dataset

---

.github/workflows/nightly.yml
ci/nightly/build-libtiledb.sh
ci/nightly/build-libtiledbvcf.sh
ci/nightly/build-tiledbvcf-py.sh
ci/nightly/environment.yaml
ci/nightly/test-libtiledbvcf.sh

Nightly build against nightly libtiledb. Will add macOS and Windows builds in the future. The main blocker is finding a compatible pyarrow. I've tried multiple versions of pyarrow, installed via either pip or conda, and I can't find an option that successfully builds for both Linux and macOS.
cc: @ihnorton, @awenocur

Add nightly build (linux only for now)

---

docker/Dockerfile-py

The Docker build started failing during the step to build arrow from source. This is a known issue that was reported a few days ago in https://github.com/apache/arrow/issues/37803 and fixed by pinning `setuptools_scm<8.0.0` in PR https://github.com/apache/arrow/pull/37819

Pin setuptools_scm<8.0.0 to build arrow from source in Dockerfile

---

apis/python/setup.py
ci/nightly/build-tiledbvcf-py.sh

It is easy to pass `--libtiledbvcf` to `python setup.py install`, but this is trickier when trying to build with `pip install`. This PR adds the additional option of specifying the env var `LIBTILEDBVCF_PATH`, though `--libtiledbvcf` takes precedence
This is similar to what is currently done in [TileDB-Py](https://github.com/TileDB-Inc/TileDB-Py/blob/dev/setup.py#L577-L579) and [TileDB-SOMA](https://github.com/single-cell-data/TileDB-SOMA/blob/7a0d937718077310fde128840a972230007b7694/apis/python/setup.py#L43-L60)

Enable LIBTILEDBVCF_PATH to be set as an environment variable

---

.azure-pipelines.yml
apis/java/CMakeLists.txt
apis/python/setup.py
apis/spark/CMakeLists.txt
apis/spark3/CMakeLists.txt

motivation: libarrow migrated to c++17 [about a year ago](https://github.com/apache/arrow/commit/9d6598108c4fd93be89f8f5becaa7cb66f929fe7)
xref: #537
cc: @gspowley @awenocur @Shelnutt2 @ihnorton

Update to c++17

---

ci/azure-linux_mac.yml
libtiledbvcf/src/read/reader.cc

When deleting a sample, the records need to be read in sorted order so the stats arrays can be updated without violating the global order.

Sort reads during sample delete

---

libtiledbvcf/src/read/reader.cc

This fixes an issue where a variant with only REF calls would not pass the IAF filter.

Allow REF calls to pass the IAF filter

---

apis/python/tests/test_tiledbvcf.py
libtiledbvcf/src/read/reader.cc
libtiledbvcf/test/inputs/gvcf-export/s0.vcf
libtiledbvcf/test/inputs/gvcf-export/s1.vcf
libtiledbvcf/test/inputs/gvcf-export/s2.vcf
libtiledbvcf/test/inputs/gvcf-export/s3.vcf
libtiledbvcf/test/inputs/gvcf-export/s4.vcf

This fixes an issue where a variant with all GT values missing (for example, a gVCF block) would not pass the IAF filter.

Allow calls with missing genotypes to pass the IAF filter

---

Makefile
libtiledbvcf/src/utils/utils.cc
libtiledbvcf/test/run-cli-tests.sh
libtiledbvcf/test/src/unit-c-api-reader.cc

Fix an issue parsing '=' in tiledb config values, as described in #603.

Handle '=' in tiledb config values

---

libtiledbvcf/src/read/reader.cc

PR #479 stopped loading the VCF headers for all in-memory exports and relied on the "first" VCF header to decode FILTER, INFO, and FORMAT fields.
PR #479 works fine when all samples have the same VCF header. However, it causes an issue when samples have different FILTER lists because the filter_id (stored as an int) needs the original VCF header when decoding back to the FILTER string.
This PR reverts the change in #479.

Load VCF headers when required for in-memory exports

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/stats/column_buffer.h

Read VCF headers with the `ManagedQuery` API which:
1. Reduces memory usage by reserving buffer space using `std::vector<T>::reserve()` instead of allocating and populating user buffers. The `ManagedQuery` uses the actual amount of memory required, while the previous implementation used the entire estimated buffer size, which was pessimistic.
2. Improves performance by avoiding populating the estimated buffer size with empty data.
This PR also resolves an edge case where reading the first sample would fail if the first sample was previously deleted.

Reduce memory usage and improve perf when reading VCF headers

---

.github/workflows/quarto-render.yml

Every time I sync the main branch on my fork, the quarto-render workflow fails. This PR updates the workflow to only deploy to gh-pages on the primary repository

Don't deploy docs on forks

---

.azure-pipelines.yml
.github/workflows/macos.yml

This is the start of the migration from Azure to GitHub Actions. I started with the macOS CI because this is currently a bottleneck due to issues finding a suitable PyPI wheel for TileDB-Py. Thus this PR supersedes #628
Some notes:
* After the libtiledbvcf build completes, it is uploaded as an artifact, and then each API package is built in parallel using the same libtiledbvcf artifact
* Due to some runtime linking issues that I am still troubleshooting, I also added an independent job, `python-standalone`, that tests building libtiledbvcf and tiledbvcf-py from a single `python -m pip install .`. The Python test suite is run in this independent job
* The build is stuck on `macos-11` because the htslib configuration step failed on both `macos-12` and `macos-13`
* This CI workflow will only …

Migrate macOS CI to GitHub Actions

---

libtiledbvcf/src/write/writer.cc

Check if an ingestion query buffer is non-empty before clearing the buffer to avoid an edge case during VCF ingestion that generates this error:
```
[TileDB::Query] Error: Cannot set buffer; sample buffer is null
```

Only clear non-empty buffers during ingestion

---

apis/python/src/tiledbvcf/dask_functions.py
apis/python/tests/test_dask.py
documentation/how-to/perform-distributed-queries-with-dask.md

Closes #671 
[dask 2024.3.0](https://docs.dask.org/en/stable/changelog.html#v2024-3-0), released two days ago on 2024-03-11, changed the default behavior of `dask.dataframe` to require the package dask-expr, but didn't add dask-expr to its default dependencies  
So our options are 1) install dask-expr for all our CI jobs, or 2) disable query-planning. According to @awenocur, we are dropping support for dask in the next couple of months, so the choice doesn't matter much. I chose option 2 since it required fewer edits.
xref: first discovered in #669 (such bad timing on my part; opened that PR the day dask broke our CI), solution confirmed in #670

Disable dask query-planning

---

.github/workflows/nightly.yml

Bump macOS nightly release branch to 2.20

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/enums/attr_datatype.h

Reduce the time to open a VCF dataset by opening the `vcf_header` and `data` arrays in parallel.
[sc-44880]

Open vcf_header and data arrays in parallel

---

.gitignore
Makefile
apis/java/src/main/java/io/tiledb/libvcfnative/NativeLibLoader.java
apis/python/tests/test_tiledbvcf.py
libtiledbvcf/cmake/Modules/FindHTSlib.cmake
libtiledbvcf/src/CMakeLists.txt
libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/stats/allele_count.cc
libtiledbvcf/src/stats/array_buffers.cc
libtiledbvcf/src/stats/array_buffers.h
libtiledbvcf/src/stats/column_buffer.cc
libtiledbvcf/src/stats/column_buffer.h
libtiledbvcf/src/stats/managed_query.h
libtiledbvcf/src/stats/sample_stats.cc
libtiledbvcf/src/stats/sample_stats.h
libtiledbvcf/src/stats/variant_stats.cc
libtiledbvcf/src/write/writer.cc
libtiledbvcf/src/write/writer_worker_v4.cc
libtiledbvcf/src/write/writer_worker_v4.h

Write sample level statistics to a new `sample_stats` array during ingestion, which enables reporting sample level statistics for all samples without querying the entire dataset.
The stats reported are similar to `bcftools stats` and `hail.sample_qc`. For example:

Create sample stats during ingestion

---

.github/workflows/nightly.yml

The recent fix for CMake 3.29.1 was backported to [`release-2.21`](https://github.com/TileDB-Inc/TileDB/tree/release-2.21) (https://github.com/TileDB-Inc/TileDB/pull/4864)
Closes #694

Bump nightly release branch to 2.21

---

apis/python/CMakeLists.txt

Fix an issue introduced in #701 by providing a list of shared libs to install explicitly.

Fix python cmake issue

---

libtiledbvcf/cmake/Modules/FindHTSlib.cmake

This is the latest available version in https://github.com/TileDB-Inc/m2w64-htslib-build; there is also version 1.19.1 which is used on non-Windows.
Fixes compile errors in places that use `VCF_INS` and `VCF_DEL`, including here: https://github.com/TileDB-Inc/TileDB-VCF/blob/964be5c736f89675d9308d4eecd7e07294319d1d/libtiledbvcf/src/stats/sample_stats.cc#L238

Use HTSlib 1.19.0 on Windows.

---

libtiledbvcf/src/read/reader.cc
libtiledbvcf/test/src/unit-c-api-reader.cc

A `vfs` based sanity check does not work with `tiledb://` URIs. Use an `Object` based check instead.

Fix an issue reading BED arrays from tiledb URIs

---

apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.c
apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.h
apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.java
apis/java/src/main/java/io/tiledb/libvcfnative/VCFReader.java
apis/java/src/test/java/io/tiledb/libvcfnative/VCFReaderTest.java
apis/python/src/tiledbvcf/binding/libtiledbvcf.cc
apis/python/src/tiledbvcf/binding/reader.cc
apis/python/src/tiledbvcf/binding/reader.h
apis/python/src/tiledbvcf/dataset.py
apis/python/tests/test_tiledbvcf.py
libtiledbvcf/src/c_api/tiledbvcf.cc
libtiledbvcf/src/c_api/tiledbvcf.h
libtiledbvcf/src/cli/tiledbvcf.cc
libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/read/reader.h
libtiledbvcf/src/utils/utils.cc
libtiledbvcf/src/utils/utils.h
libtiledbvcf/src/vcf/region.cc
libtiledbvcf/test/src/unit-c-api-reader.cc

Read BED files stored in a TileDB filestore. This enables reading BED files registered on TileDB Cloud, which supports complex object store credentials.
The read API is simplified by unifying the parameter used to pass in a BED file, BED file registered on TileDB Cloud, or a BED array. The separate BED array parameter is removed.

Read BED files stored as TileDB files

---

.azure-pipelines.yml
apis/java/build.gradle
apis/spark/build.gradle
apis/spark3/build.gradle
ci/native_libs-linux_osx.yml

The goal of this PR is to remove the manual step of bumping the Java/Spark version for every release.
The `build.gradle` files try to read the version from a git tag or a `version.txt` file in the root of the repo, which is added to the build artifacts during the `BuildNativeLibs` CI task.

Set java/spark version from git tag

---

apis/python/conda-env.yml
apis/python/pyproject.toml
ci/gha-win-env.yml
ci/nightly/requirements.txt

Both the nightlies in this repo (#730) and my centralized nightlies (https://github.com/jdblischak/centralized-tiledb-nightlies/issues/12#issuecomment-2176240410) have been failing for a week due to the release of numpy 2. PRs #731 and #732 have the numpy<2 pin, but they are still undergoing review. To fix the nightly builds, I cherry-picked @awenocur's commit to pin numpy<2.

Hotfix: pin numpy < 2

---

.github/workflows/macos.yml

Discovered in #734. macos-11 will be retired this Friday
> This is a scheduled macOS-11 brownout. The macOS-11 environment is deprecated and will be removed on June 28th, 2024.
The nightly runs on macos-12, so this should be possible
https://github.com/TileDB-Inc/TileDB-VCF/blob/7ff0bacababf61ffff6d94ba2f3e3d447557b20e/.github/workflows/nightly.yml#L25

Migrate macOS CI to macos-12 runner

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc

Add the metatdata group to the VCF dataset, so the on-disk group will be deleted by recursive group delete functions.

Add the metadata group to the VCF dataset

---

apis/python/tests/test_tiledbvcf.py
libtiledbvcf/src/CMakeLists.txt
libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/read/in_memory_exporter.cc
libtiledbvcf/src/read/read_query_results.h
libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/stats/variant_stats.cc
libtiledbvcf/src/stats/variant_stats.h
libtiledbvcf/src/stats/variant_stats_reader.cc
libtiledbvcf/src/stats/variant_stats_reader.h
libtiledbvcf/src/utils/normalize.cc
libtiledbvcf/src/utils/normalize.h
libtiledbvcf/src/write/writer.cc
libtiledbvcf/test/inputs/stats/first.vcf
libtiledbvcf/test/inputs/stats/second.vcf
libtiledbvcf/test/run-cli-tests.sh

Take ref blocks into account when computing AF, and make two new fields: `info_TILEDB_IAC` and `info_TILEDB_IAN` available to data frames.

Add Hail-like AC, AN, and AF computation to variant stats V3

---

.github/workflows/nightly.yml
ci/nightly/build-tiledb-py.sh
ci/nightly/build-tiledbvcf-py.sh
ci/nightly/requirements.txt

Fixes #747
The nightly builds are no longer failing due to the use of deprecated APIs. However, now it is failing to build dev TileDB-Py from source (https://github.com/TileDB-Inc/TileDB-VCF/issues/747#issuecomment-2273415744).
I updated the nightly workflow to build TileDB-Py with scikit-build-core and also to set `TILEDB_REMOVE_DEPRECATIONS=OFF`. However, despite this being essentially identical to my setup in my centralized nightlies, TileDB-Py can't find libtiledb at runtime (at least that is my assumption for the failed import test). The only difference is that my [centralized nightlies perform an editable install](https://github.com/jdblischak/centralized-tiledb-nightlies/blob/ec5ce1f3d9cd1d01f799a7d0f1faa76184d2d73d/.github/workflows/linux.yml#L127).
@dudoslav do you have any …

Migrate TileDB-Py to scikit-build-core and don't check for deprecations

---

libtiledbvcf/src/stats/sample_stats.cc
libtiledbvcf/src/stats/variant_stats.cc
libtiledbvcf/src/stats/variant_stats.h

The computation of variant statistics was improved in [0.33.0](https://github.com/TileDB-Inc/TileDB-VCF/releases/tag/0.33.0). This PR handles writing to the `sample_stats` and `variant_stats` arrays created before version 0.33.0.

Handle legacy stats arrays

---

apis/python/src/tiledbvcf/binding/libtiledbvcf.cc
apis/python/src/tiledbvcf/binding/writer.cc
apis/python/src/tiledbvcf/binding/writer.h
apis/python/src/tiledbvcf/dataset.py
apis/python/tests/test_tiledbvcf.py
libtiledbvcf/src/c_api/tiledbvcf.cc
libtiledbvcf/src/c_api/tiledbvcf.h
libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/write/writer.cc
libtiledbvcf/src/write/writer.h

Add a Python API to delete samples.

add Python API for sample deletion

---

apis/python/src/tiledbvcf/dataset.py
apis/python/tests/test_tiledbvcf.py

Add context manager support to the Python `Dataset` class.
```python
import tiledbvcf
ds_uri = "..."
with tiledbvcf.Dataset(ds_uri) as ds:
num_records = ds.count()
```
For code that doesn't use the context manager, a separate `close` method is available.
```python
import tiledbvcf
ds_uri = "..."
ds = tiledbvcf.Dataset(ds_uri)
num_records = ds.count()
ds.close()
```

Add Dataset close and context manager support to the Python API

---

apis/python/src/tiledbvcf/dataset.py
apis/python/tests/test_tiledbvcf.py

Reset the reader object to allow multiple calls to `read_iter`.

Update to allow multiple calls to read_iter

---

libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

Upgrade to TileDB 2.26.0

---

apis/python/src/tiledbvcf/dataset.py
apis/python/tests/test_tiledbvcf.py

Add `Dataset.delete` to the Python API, which deletes TileDB-VCF datasets stored on the local file system, remote object store, or registered on TileDB Cloud.
For example:
```python
ds_uri = ...
tiledbvcf.Dataset.delete(ds_uri)
```

Add Dataset delete to the Python API

---

apis/python/tests/test_tiledbvcf.py

Modify delete dataset test to use `os.path.exists` to check for dataset existence.

Fix delete dataset test

---

apis/python/src/tiledbvcf/allele_frequency.py

The type hint for the return instantiates a dataframe rather than just hints. This doesn't really cause an issue, but does cause that dataframe to be created whenever importing `tiledbvcf` do to this module being imported in top-level `__init__.py`

type return incorrectly inst an object

---

libtiledbvcf/src/read/in_memory_exporter.cc

In order to fix an issue with newer compilers we have to remove any usage of VLA from VCF code. I am not sure how this changes the performance of the code, but for now I decided to use `std::vector`. If we could bound the size of the array we could use `std::array` and have the memory allocated on stack.
https://github.com/TileDB-Inc/tiledb-vcf-feedstock/pull/141#issuecomment-2450369283

Change VLA code by using std::vector

---

.azure-pipelines.yml
.github/workflows/nightly.yml
ci/azure-linux_mac.yml
ci/native_libs-linux_osx.yml

This PR has multiple motivations:
* `ubuntu-latest` will be Ubuntu 24 on [Dec 5th](https://github.blog/changelog/2024-11-05-notice-of-breaking-changes-for-github-actions/)
* The [centralized-tiledb-nightlies](https://github.com/TileDB-Inc/centralized-tiledb-nightlies) repo has migrated to Ubuntu 24 in order to update GCC from 11 to 13 to accommodate the recent transition of TileDB-SOMA to C++20 (https://github.com/TileDB-Inc/centralized-tiledb-nightlies/pull/27, https://github.com/single-cell-data/TileDB-SOMA/issues/3154). libtiledbvcf cannot be compiled with GCC 13, and when it is built with GCC 11, it fails to link against libtiledb that was built with GCC 13 (https://github.com/TileDB-Inc/centralized-tiledb-nightlies/issues/28)

Run CI on Ubuntu 24 (GCC 13)

---

libtiledbvcf/src/write/writer.cc

During VCF ingestion, explicitly check that the query buffers are non-empty using `utils::query_buffers_set` before clearing the buffers.

More robust non-empty buffer check during ingestion

---

.github/workflows/nightly.yml
apis/python/pyproject.toml

Update the nightly since `libtiledb` and `tiledb-py` renamed the `dev` branch to `main`.
Also added the `"setuptools-scm>=8.1.0"` requirement based on recent issues with tiledb-vcf-feedstock.
Resolves #797.

Clone main branch in nightly

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/vcf/vcf_utils.cc

Retry `vcf_open` in `VCFUtils::hdr_read_header` to handle intermittent read issues.

Retry vcf_open in VCF read header function

---

.github/workflows/nightly.yml

Closes #805 
Run `apt-get update` to get the latest security patch for liblzma-dev

Update APT in nightly builds

---

libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

Update to TileDB Embedded 2.28.0-rc0

Update to TileDB Embedded 2.28.0-rc0

---

.github/workflows/nightly.yml

Building TileDB core from the branch `release-2.28` should fix the bzip2 download errors due to the flaky URL (https://github.com/TileDB-Inc/TileDB-VCF/issues/808#issuecomment-2794250839)

Bump nightly build release branch to 2.28

---

libtiledbvcf/cmake/Modules/FindSpdlog.cmake
libtiledbvcf/src/vcf/vcf_merger.cc

This required adding an include of `fmt/ranges.h` because of [a bug in libfmt 11](https://stackoverflow.com/a/79248376), which spdlog depends on.

Updated spdlog to version 1.15.3

---

libtiledbvcf/cmake/Modules/FindSpdlog.cmake
libtiledbvcf/src/vcf/vcf_merger.cc

Reverts TileDB-Inc/TileDB-VCF#82 because this change is causing the [nightly build on Ubuntu 24.04 to fail](https://github.com/TileDB-Inc/TileDB-VCF/issues/823). Will revisit when a release is not imminent.

Revert "Updated spdlog to version 1.15.3"

---

libtiledbvcf/src/read/delete_exporter.cc
libtiledbvcf/src/read/exporter.cc
libtiledbvcf/src/read/exporter.h

An exporter is used to handle deletions, meaning variants are converted to BCF records so that they can be "exported." This conversion (specifically, loading info and format fields) is a hot spot in the deletion code path. Since the deletion exporter only needs the genotype format field, this PR updates the exporter code to only load that field when making a deletion.

Improve run-time performance of delete exporter

---

libtiledbvcf/src/utils/buffer.cc

This is to improve deletion run-time performance.
Note that the `value(...)` method may be similarly updated, but there's an edge case where the last offset is missing. Fortunately the `value(...)` method's impact on deletion run-time performance is negligible so it will remain unchanged in this PR.

Update the Buffer class data() method to compute string view directly from offsets

---

libtiledbvcf/src/cli/tiledbvcf.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/dataset/tiledbvcfdataset.h
libtiledbvcf/test/run-cli-tests.sh
libtiledbvcf/test/src/unit-vcf-delete.cc

This PR makes changes to ensure that the deletion operation stays within its memory budget, especially when deleting multiple samples. Specifically:
* Samples are deleted one at a time but there was a bug that updated the stats for all samples simultaneously, which used a lot of memory. This has been fixed.
* The deletion memory budget was previously hard-coded. This can now be controlled via CLI flags.
* The memory budget of the dataset object performing the deletion was previously unbounded. Now this is also controlled by the previously mentioned CLI flags.
* Previously there were no unit or CLI tests for deletions! These have been added.

Deletion memory usage

---

.github/workflows/nightly.yml

Closes #841 
I split these commits off of #840. The goal of this PR is limited to fixing the currently failing nightly builds. It defines `SDKROOT` to address the recent changes in CMake 4.0 (https://github.com/TileDB-Inc/TileDB/pull/5633) and also updates the maintainers assigned to nightly-failure Issues.

 Define SDKROOT to fix failing macOS nightly builds

---

.github/workflows/macos.yml
.github/workflows/nightly.yml

The CI worked with both macos-14 and macos-15 (#840). My understanding is that they are both arm64, so we may as well jump to the later one.

Migrate to macos-15
