TileDB-Inc/TileDB-VCF

apis/python/src/tiledbvcf/dataset.py

This is a usability improvement for the python api

Support TileDB-Py Config or dicts for reader conf

---

LICENSE

Add main LICENSE file

---

libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

Update TileDB for superbuild to 1.7.5

Update TileDB for superbuild to 1.7.5

---

apis/spark/build.gradle
apis/spark/src/main/java/io/tiledb/vcf/VCFInfoFmtDecoder.java
apis/spark/src/main/java/io/tiledb/vcf/VCFPartitionInfo.java

Add spark publishing for source and to local maven

Add spark publishing for source and to local maven

---

apis/spark/src/main/java/io/tiledb/libvcfnative/VCFReader.java
apis/spark/src/main/java/io/tiledb/vcf/Util.java
apis/spark/src/main/java/io/tiledb/vcf/VCFInputPartitionReader.java
apis/spark/src/test/java/io/tiledb/vcf/UtilTest.java

Contains validity checks on
- Buffer Size (should be < 2048MB)
- Long to Int conversion

Validity Checks

---

.gitignore
apis/spark/build.gradle
apis/spark/src/main/java/io/tiledb/util/CredentialProviderUtils.java
apis/spark/src/main/java/io/tiledb/vcf/VCFDataSourceOptions.java
apis/spark/src/main/java/io/tiledb/vcf/VCFInputPartitionReader.java
apis/spark/src/test/java/io/tiledb/util/CredentialProviderUtilsTest.java
apis/spark/src/test/java/io/tiledb/vcf/VCFDataSourceOptionsTest.java

Summary
* add config that takes in aws_role_arn and aws_credentials_provider for generating session tokens

Add AWS session token support

---

apis/java/src/test/java/io/tiledb/libvcfnative/VCFReaderTest.java
apis/python/src/tiledbvcf/dataset.py
apis/spark/src/main/java/io/tiledb/util/CredentialProviderUtils.java
apis/spark/src/main/java/io/tiledb/vcf/VCFDataSourceOptions.java
apis/spark/src/main/java/io/tiledb/vcf/VCFInputPartitionReader.java
apis/spark/src/test/java/io/tiledb/util/CredentialProviderUtilsTest.java
apis/spark/src/test/java/io/tiledb/vcf/VCFDataSourceOptionsTest.java

Fix dataset for python3.6

---

libtiledbvcf/src/read/reader.cc

Fix segfault in sample_id being out of range

Fix segfault in sample_id being out of range

---

apis/python/.gitignore
apis/python/setup.py
apis/python/src/tiledbvcf/__init__.py

This allows for the version number to be automatically generated

Add support for setuptools_scm with python api

---

.azure-pipelines.yml

Specifies a vmImage for the docker build job.

Small fix for CI docker image builds

---

apis/java/build.gradle
apis/spark/build.gradle

Reverts TileDB-Inc/TileDB-VCF#84

Revert "Use gradle-git-version for java/spark versioning"

---

apis/spark/build.gradle

Allow publishing the shadow jar to maven/local maven

Allow publishing the shadow jar to maven/local maven

---

apis/java/build.gradle
apis/spark/build.gradle
libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

Update TileDB to 2.0.3 for superbuild

Update TileDB to 2.0.3 for superbuild

---

apis/java/build.gradle
apis/spark/build.gradle

Update version for 0.5.0 snapshot

Update version for 0.5.0 snapshot

---

apis/python/tests/test_tiledbvcf.py
apis/spark/src/main/java/io/tiledb/vcf/VCFSparkSchema.java
libtiledbvcf/src/c_api/arrow.h
libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/read/in_memory_exporter.cc
libtiledbvcf/test/src/unit-c-api-reader.cc
libtiledbvcf/test/src/unit-vcf-export.cc

fmt_DP, fmt_GQ, fmt_PS, fmt_PQ, fmt_MQ and fmt_DP_MIN should be single values

fmt_DP, fmt_GQ, fmt_PS, fmt_PQ, fmt_MQ and fmt_DP_MIN should be single values

---

apis/spark/src/main/java/io/tiledb/vcf/VCFInputPartitionReader.java

Add spark task stage/ID to partition reader logs

Add spark task stage/ID to partition reader logs

---

apis/python/tests/test_tiledbvcf.py
libtiledbvcf/test/run-cli-tests.sh

Adds cli/py tests for testing against bug fixed in #142

Add array and cli/py tests for querying records with null attributes

---

apis/java/build.gradle
apis/spark/build.gradle

Set Spark/Java version to 0.5.0 release

Set Spark/Java version to 0.5.0 release

---

apis/java/build.gradle
apis/spark/build.gradle

Update spark/java version to 0.5.1-SNAPSHOT

Update spark/java version to 0.5.1-SNAPSHOT

---

apis/python/src/tiledbvcf/dask_functions.py

This option allows to stop reading after a given number of partitions (for debugging and resource estimation).
---
[ch3030]

Add limit_partitions kwarg option for read_dask/map_dask

---

apis/java/src/main/java/io/tiledb/libvcfnative/NativeLibLoader.java

Log all errors for java native lib loading

Log all errors for java native lib loading

---

libtiledbvcf/src/read/reader.cc

In verbose mode new output is given for bed file parsing and sorting times.

Add timing for parsing and sorting bed file

---

.azure-pipelines.yml
ci/collect-nativelibs.sh

This updates the GitHub Release task to publish a draft and includes a few other minor tweaks.

Switch GitHub Release to Drafts

---

apis/java/build.gradle
apis/spark/build.gradle

Update java/spark version to 0.5.3-SNAPSHOT

Update java/spark version to 0.5.3-SNAPSHOT

---

libtiledbvcf/src/read/exporter.cc

Previously we always tried to update the END field in the info of the header for VCF record exports. This caused errors if the END field did not exist in the header. Now we conditionally update it.

Validate END exists before updating on export

---

libtiledbvcf/test/run-cli-tests.sh

All cli tests diffs should be reported. This will help with the CLI failure in #176

All cli tests diffs should be reported

---

libtiledbvcf/src/utils/sample_utils.h

Previously remote files were downloaded to a temporary local file with a fixed name, which could create conflicts when running batch ingest from a single node.

Download files to sample-specific temp locations

---

apis/java/build.gradle
apis/spark/build.gradle

Update spark/java version to 0.6.0-SNAPSHOT

Update spark/java version to 0.6.0-SNAPSHOT

---

libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

Update to TileDB 2.1.1

---

libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

Update TileDB to 2.1.3

---

apis/java/build.gradle
apis/spark/build.gradle

Update spark/java versions for 0.6.1 release

Update spark/java versions for 0.6.1 release

---

libtiledbvcf/src/c_api/tiledbvcf.cc
libtiledbvcf/src/c_api/tiledbvcf.h
libtiledbvcf/src/cli/tiledbvcf.cc
libtiledbvcf/src/write/writer.cc
libtiledbvcf/src/write/writer.h

Add support for printing tiledb statistics on ingest

Add support for printing tiledb statistics on ingest

---

apis/python/setup.py
apis/python/src/tiledbvcf/__init__.py
apis/python/src/tiledbvcf/dask_functions.py
apis/python/src/tiledbvcf/dataset.py
apis/python/tests/test_dask.py
apis/python/tests/test_tiledbvcf.py

Format with black

---

ci/azure-linux_mac.yml
ci/native_libs-linux_osx.yml

Workaround taken from github actions issue:
https://github.com/actions/virtual-environments/issues/1811

Workaround homebrew openssl error for CI

---

libtiledbvcf/src/read/reader.cc

This solves a performance regression introduced in v0.6 when the read algorithm was improved. The changes are to move the string comparison of contig until after we've checked all integer based conditions. Second, and more impactful, exit the intersection check early if the regions have moved pasted the record. The regions are sorted so this early exit is safe.

Optimize v2/v3 read queries

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/htslib_plugin/hfile_tiledb_vfs.c
libtiledbvcf/src/read/in_memory_exporter.h

This is a very minor leak, but was easy to fix.

Fix leaking of hfile*

---

apis/aws-batch/batch-export.py
apis/aws-batch/batch-ingest.py
apis/aws-batch/batchmetrics.py
ci/azure-linux_mac.yml
scripts/generate-synthetic-sample.py

Add python format and linting check

Add python format and linting check

---

libtiledbvcf/src/read/reader.cc

This reduces the number of times we read the VCF headers drastically in v4 arrays to once per sample batch instead of sample batch * number of contigs.
This should be merged after #206

 Only fetch vcf headers on a new read sample batch

---

libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/vcf/region.h
libtiledbvcf/src/write/writer.cc

Sort v4 regions in lexicographical order for writes

Sort v4 regions in lexicographical order for writes

---

apis/python/src/tiledbvcf/dask_functions.py
apis/python/src/tiledbvcf/dataset.py

Reverts TileDB-Inc/TileDB-VCF#198
The dask dataframe change looked good but after merging CI is failing so reverting for now.

Revert "Build Chunked Arrow Table in _read_partition()"

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc

The API was switched to a std::array to be consistent with other API functions and because the return values were changed to all be byte counts instead of a mix of byte and element counts.
This is currently handled with a pre-processor. We will drop that when we move to an official 2.2 release.

Support TileDB 2.2 C++ result estimate API changes

---

libtiledbvcf/src/read/reader.cc

Since TileDB queries now run on a single contig, we no longer need to check each record to make sure it matches the previous records contig, and optionally lookup the new contig regions. Instead we can lookup contig regions once before we process the cells. We can now also remove the need to build the contig string in the looping of the cells.

Remove contig check from process_query_results_v4

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/test/run-cli-tests.sh

Only print row_tile_extent for v2/v3 datasets

Only print row_tile_extent for v2/v3 datasets

---

libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

This includes a number of performance improvements for string dimensions and handling a large number of fragments.

Update to TileDB 2.1.5

---

apis/java/build.gradle
apis/spark/build.gradle

Update java/spark for 0.7.1-SNAPSHOT

Update java/spark for 0.7.1-SNAPSHOT

---

libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

Update TileDB to 2.2.3

---

libtiledbvcf/src/cli/tiledbvcf.cc

Fix typo in vacuum command

---

libtiledbvcf/src/read/reader.cc

Add verbose output to memory budget calculations

Add verbose output to memory budget calculations

---

libtiledbvcf/src/read/reader.cc

Set config on query after reset

Set config on query after reset

---

libtiledbvcf/src/read/reader.cc

Add verbose message on double buffering

Add verbose message on double buffering

---

apis/java/build.gradle
apis/spark/build.gradle

Update Java/Spark versions for 0.8.2 release

Update Java/Spark versions for 0.8.2 release

---

apis/python/conda-env.yml

Update conda env for pyarrow 3.0

Update conda env for pyarrow 3.0

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc

Fix GCC 4.8.5 build issue

---

apis/java/build.gradle
apis/spark/build.gradle

Update Java/Spark version to 0.8.5

Update Java/Spark version to 0.8.5

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/test/src/unit-c-api-reader.cc

This solves a problem where the materialized fields sometimes failed to load.

materialized_attribute_loaded_ needs to be inited

---

libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

Update to TileDB 2.2.6

---

apis/java/build.gradle
apis/spark/build.gradle

Update Java/Spark version to 0.8.6

Update Java/Spark version to 0.8.6

---

libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

Update to TileDB 2.2.8

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc

Add error checking to v4 header parsing on fetch

Add error checking to v4 header parsing on fetch

---

apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.c
apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.h
apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.java
apis/java/src/main/java/io/tiledb/libvcfnative/NativeLibLoader.java
apis/java/src/main/java/io/tiledb/libvcfnative/VCFReader.java
apis/python/src/tiledbvcf/binding/libtiledbvcf.cc
apis/python/src/tiledbvcf/binding/reader.cc
apis/python/src/tiledbvcf/binding/reader.h
apis/python/src/tiledbvcf/binding/writer.cc
apis/python/src/tiledbvcf/binding/writer.h
apis/python/src/tiledbvcf/dataset.py
libtiledbvcf/src/c_api/tiledbvcf.cc
libtiledbvcf/src/c_api/tiledbvcf.h
libtiledbvcf/src/cli/tiledbvcf.cc
libtiledbvcf/src/utils/utils.cc
libtiledbvcf/src/utils/utils.h

Add version function to c-api/python/java and print version to logs on java jar loading.

Add version function to c-api/python/java/spark

---

apis/java/build.gradle
apis/spark/build.gradle

Update java/spark version to 0.8.8

Update java/spark version to 0.8.8

---

apis/spark/src/main/java/io/tiledb/vcf/VCFDataSourceOptions.java
apis/spark/src/main/java/io/tiledb/vcf/VCFInputPartitionReader.java

Print spark options at info level in log

Print spark options at info level in log

---

libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

Update to TileDB 2.2.9

---

apis/java/src/main/java/io/tiledb/libvcfnative/README.md

Add README.md documenting LibVCFNative update

---

apis/java/build.gradle
apis/spark/build.gradle

Update Java/Spark version for 0.8.9

Update Java/Spark version for 0.8.9

---

apis/java/build.gradle
apis/spark/build.gradle
libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake
libtiledbvcf/src/dataset/attribute_buffer_set.cc

Update to TileDB 2.3.0

---

libtiledbvcf/CMakeLists.txt
libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

Update to TileDB 2.3.1

---

libtiledbvcf/src/read/reader.cc
libtiledbvcf/test/src/unit-c-api-reader.cc

Fix typo in setting compute levels

Fix typo in setting compute levels

---

apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.c
apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.h
apis/python/src/tiledbvcf/binding/libtiledbvcf.cc
apis/python/src/tiledbvcf/binding/reader.cc
apis/python/src/tiledbvcf/binding/reader.h
apis/python/src/tiledbvcf/binding/writer.cc
apis/python/src/tiledbvcf/binding/writer.h
ci/azure-linux_mac.yml

* Update CI script to run clang-format on code in the `apis` tree. 
* Check in clang formatted code to set baseline for future changes.

Run clang-format on api code

---

.azure-pipelines.yml

Use 'TileDB-Inc-Release' connection for GithubRelease

---

.azure-pipelines.yml
apis/java/build.gradle
apis/python/tests/test_dask.py
apis/spark/build.gradle
docker/Dockerfile-cli
docker/Dockerfile-py
libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

Update to TileDB 2.4.0

---

apis/java/build.gradle
apis/spark/build.gradle

Update spark/java version for 0.11.1

Update spark/java version for 0.11.1

---

libtiledbvcf/src/utils/utils.cc

Update function used to detect system memory on macos.

Update system_memory_mb() for macos

---

libtiledbvcf/src/read/reader.cc

Set `sm.mem.total_budget` for read queries. The default is 10GB, but we can get better performance by providing more memory when available.

Set TileDB total memory budget

---

docker/Dockerfile-py
libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

Update to TileDB 2.5.3

---

apis/java/build.gradle
apis/spark/build.gradle

Update java/spark for version 0.12.2

Update java/spark for version 0.12.2

---

apis/java/build.gradle
apis/spark/build.gradle
libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

Update to TileDB 2.6.0

---

apis/java/build.gradle
apis/spark/build.gradle
libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

Upgrade to TileDB 2.6.2

---

.github/workflows/backport.yml

Add backport bot for release branching support

Add backport bot for release branching support

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc
libtiledbvcf/src/write/writer.cc

Update resume ingestion code to fix issues skipping the last contig and handling merged contigs.

Update resume ingestion

---

CONTRIBUTING.md
README.md

fixed broken doc subsection link, added all doc subsections, added blog

fix broken doc subsection link

---

libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

Update superbuild to TileDB 2.11.3

Update superbuild to TileDB 2.11.3

---

apis/java/build.gradle
apis/spark/build.gradle
apis/spark3/build.gradle

Bump java/spark version for pending release of 0.19.1

Bump java/spark version for pending release of 0.19.1

---

apis/java/build.gradle
apis/spark/build.gradle
apis/spark3/build.gradle
libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

Story details: https://app.shortcut.com/tiledb-inc/story/22758

Upgrade to TileDB 2.12.0

---

apis/java/build.gradle
apis/spark/build.gradle
apis/spark3/build.gradle
libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

Story details: https://app.shortcut.com/tiledb-inc/story/23241

Update TileDB-VCF to 0.20.2

---

libtiledbvcf/src/write/writer.cc

During ingestion, finalize VCF data fragment after stats array and anchor fragments have been finalized. This ensures that valid stats array and anchor array fragments will exist if the corresponding data fragment exists.

Finalize data fragments last during ingestion.

---

libtiledbvcf/src/utils/sample_utils.cc

Check for empty ingestion

---

libtiledbvcf/src/dataset/tiledbvcfdataset.cc

Improve performance of loading VCF headers, while considering the first sample may have been deleted.

Improve performance of loading VCF headers

---

apis/java/build.gradle
apis/spark/build.gradle
apis/spark3/build.gradle
ci/azure-linux_mac.yml
libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

Release 0.19.3 with TileDB 2.11.4.

Update to TileDB 2.11.4

---

.azure-pipelines.yml
.github/workflows/quarto-render.yml
CONTRIBUTING.md
README.md
ci/build-images.yml
docker/README.md
documentation/docker/README.md
documentation/index.md
documentation/the-solution.md

* Update CI to use the `main` branch.
* Fix broken links and remove unused links in docs.

Move to main branch and fix broken links

---

apis/java/build.gradle
apis/spark/build.gradle
apis/spark3/build.gradle

Update Java/Spark for version 0.24.1

Update Java/Spark for version 0.24.1

---

libtiledbvcf/src/vcf/vcf_v4.cc

Throw an error if htslib returns an error reading VCF data.

Handle htslib errors reading VCF data

---

README.md
apis/python/setup.py
documentation/index.md

I noticed the Azure badge image said the pipeline was "never built"
xref: #527

Update branch for a few URLs

---

Makefile
libtiledbvcf/src/htslib_plugin/hfile_tiledb_vfs.c

Add VFS read retry to handle intermittent read errors.

Add retry on VFS read error

---

apis/java/build.gradle
apis/spark/build.gradle
apis/spark3/build.gradle
libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

manual backport: automatic backport failed

Backport Embedded 2.17.4 update

---

.github/workflows/nightly.yml

Closes #625 
cc: @awenocur @ihnorton

Bump release branch to 2.18 for nightly builds

---

.github/workflows/nightly.yml

Migrate to the release-2.19 branch for nightly builds

---

.github/workflows/nightly.yml

Bump nightly release branch to 2.20

---

.github/workflows/backport.yml

Update backport action to ensure that all commits from a backported PR are included.

Update backport action

---

scripts/array-size.py

A utility script to provide the size of an array broken down per column, optionally displaying the filters.
```
$ array-size.py array_uri
name     type     data  offsets  validity    total  percent
0              fmt    uint8  8483150    66593         0  8549743   50.064
1             info    uint8  5989054    54952         0  6044006   35.391
2             qual  float32   529503        0         0   529503    3.101
3          end_pos   uint32   455988        0         0   455988    2.670
4   real_start_pos   uint32   455918        0         0   455918    2.670
5       start_pos*   uint32   441214        0         0   441214    2.584
6          alleles    bytes   329757   105369         0   435126    2.548
7           fmt_GT    uint8   119494     9184         0   128678    0.753
8 …
```

Array size utility script

---

apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.c
apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.h
apis/java/src/main/java/io/tiledb/libvcfnative/LibVCFNative.java
apis/java/src/main/java/io/tiledb/libvcfnative/VCFReader.java
apis/java/src/test/java/io/tiledb/libvcfnative/VCFReaderTest.java
apis/python/src/tiledbvcf/binding/libtiledbvcf.cc
apis/python/src/tiledbvcf/binding/reader.cc
apis/python/src/tiledbvcf/binding/reader.h
apis/python/src/tiledbvcf/dataset.py
apis/python/tests/test_tiledbvcf.py
libtiledbvcf/src/c_api/tiledbvcf.cc
libtiledbvcf/src/c_api/tiledbvcf.h
libtiledbvcf/src/cli/tiledbvcf.cc
libtiledbvcf/src/read/reader.cc
libtiledbvcf/src/read/reader.h
libtiledbvcf/src/utils/utils.cc
libtiledbvcf/src/utils/utils.h
libtiledbvcf/src/vcf/region.cc
libtiledbvcf/test/src/unit-c-api-reader.cc

(cherry picked from commit 394059317326a64e1bce43a37f8ef4d7edd46364)

[Backport release-0.31] Read BED files stored as TileDB files (#712)

---

apis/python/tests/test_tiledbvcf.py
libtiledbvcf/src/stats/variant_stats.cc
libtiledbvcf/src/stats/variant_stats.h
libtiledbvcf/src/vcf/vcf_utils.cc
libtiledbvcf/src/vcf/vcf_utils.h
libtiledbvcf/test/inputs/stats/eighth.vcf
libtiledbvcf/test/inputs/stats/fifth.vcf
libtiledbvcf/test/inputs/stats/first.vcf
libtiledbvcf/test/inputs/stats/fourth.vcf
libtiledbvcf/test/inputs/stats/second.vcf
libtiledbvcf/test/inputs/stats/seventh.vcf
libtiledbvcf/test/inputs/stats/sixth.vcf
libtiledbvcf/test/inputs/stats/third.vcf
libtiledbvcf/test/run-cli-tests.sh

Writer changes for Variant Stats

---

apis/python/src/tiledbvcf/__init__.py
apis/python/src/tiledbvcf/dask_functions.py
apis/python/src/tiledbvcf/dataset.py

Only import dask when dask related functions are called.

Lazily import dask

---

libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

Upgrade to TileDB 2.26.1

---

.azure-pipelines.yml
.github/workflows/macos.yml
.github/workflows/nightly.yml
apis/java/build.gradle
apis/java/gradle/wrapper/gradle-wrapper.properties

Add duplicatesStrategy into settings.gradle in order to fix build errors

Migrate to macos-13 runner image

---

.github/workflows/windows.yml
apis/python/tests/test_tiledbvcf.py
libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

Upgrade to TileDB 2.27.0, reduce noise in pytests, and disable windows CI until it is working again.

Upgrade to TileDB 2.27.0

---

libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

Update TileDB to release 2.28.0

Update TileDB to release 2.28.0

---

libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

Solves an issue detected here in this [action](https://github.com/r-universe/sounkou-bioinfo/actions/runs/17717361304/job/50450257679#step:5:353)

add arm64 linux source download

---

libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake

Update the TileDB version to 2.29.0.

Update TileDB core to 2.29.0
